### ISSUE TITLE
Enhancement: Create new Grocy product after scanning barcode

### ISSUE THREAD

**Issue by gkron92** [Forceu/barcodebuddy#1]
I’ve installed barcode buddy on my synology nas.  I’m not using a scanner at the moment just trying to use the examples you provided in the readme.  I tried a Cheerios barcode using showui&add and it found the barcode.  I can’t seem to get it to add to grocy though.  I clicked add but nothing happened.  I’m not sure if I put the api credentials in correctly.  When I go to the rest api documentation I see the server listed there.  Do I list that whole thing?  I have grocy installed via the hassio package.

**Comment by Forceu** [comment]
Sorry for the late reply, I did not get a notification for the issue.

Have you tried it with the current version?

**Comment by Forceu** [comment]
In theory any device should work, as long as you can read out the barcodes. I will upload an example script tomorrow on how to grab the input from the barcode scanner, provided that it registers as a keyboard.

**Comment by gkron92** [comment]
Unfoirtunately it's not working for me.  I have the barcode page up.  I scan something and nothing appears.  I also tried scanning the BBUDDY_P barcode first and then an item and same thing.  If I have grocy open and I'm in the barcode field the barcode gets populated so I know the scanner is working.

**Comment by Forceu** [comment]
Originally Barcode Buddy was not supposed to have manual entry, but the barcodes from the scanner had to be send to a script which passes it to Barcode Buddy. However I just released the first stable release, which includes an option to manually enter them as well in the web ui.

Alternatively if you are using a linux server that is connected to the barcode scanner, you can use this script: https://github.com/Forceu/barcodebuddy/blob/master/example/grabInput.py

**Comment by gkron92** [comment]
Ok but what the proper procedure to get the items into Grocy.  I was hoping barcode buddy was going to do the work of looking up a new product, get the details and add it to Grocy without having to manually enter the product into Grocy.  Is my understanding incorrect?

**Comment by Phoara** [comment]
@gkron92: Have you done anything special to make barcode buddy run on your Synology? I get an error, wenn I try to manually add a barcode.

**Comment by Forceu** [comment]
No, unfortunately this is not possible (yet), as only the name can be reliably looked up. [Here](https://world.openfoodfacts.org/product/4000400037923/classic-creamy-flavor-with-sunflower-rapeseed-and-linseed-oil-becel) is an example from the website where the lookup is done. As you can see, most entries are not relevant to Grocy, therefore it makes more sense (at the moment) to add new products manually in Grocy.

However I will keep it in mind, and maybe add such a feature at some point.

**Comment by Forceu** [comment]
Done: a7573cf26e2e035b9b2ca3cf948e8702a8d48c98
