### ISSUE TITLE
External URLs generated have extra "/"

### ISSUE THREAD

**Issue by skanur** [Forceu/barcodebuddy#104]
I'm trying to setup barcode buddy + grocy within a single docker compose file similar to [linuxserver docker images](https://docs.linuxserver.io/general/swag#using-heimdall-as-the-home-page-at-domain-root). I encountered issue similar to #61  and had to configure `EXTERNAL_GROCY_URL` to get the external redirect pointing to grocy instance. But the external hyperlinks generated has an extra "/", e.g.

`https://grocy.<domain.name>//product/new?closeAfterCreation&prefillbarcode=123456789123`

In `config.php` I have configured `BASEURL=""`, but it didn't help.

My limited knowledge of these systems hinder me from getting more debug info for you.

How can I setup barcode buddy to generate correct external hyperlinks without the extra "/" between domain name and rest of the part? Thanks in advance!

Edit: I use version 1.6.5.0 of barcode buddy app as linuxserver/grocy image is not updated to 3.0.1 yet.

**Comment by Forceu** [comment]
Thank you very much for the report! Fixed in 9c5a17e1f6faa63bc11865f61b32a8650f3ac7e6

**Comment by skanur** [comment]
Thanks for the quick response and fix!

Could you clarify if `BASEURL` should be modified to `""` in order to get this working? Or does it work out-of-the box?

**Comment by Forceu** [comment]
No that should work out of the box, but let me know if you encounter any issues!
