### ISSUE TITLE
Support setting product quantities by barcode

### ISSUE THREAD

**Issue by skanur** [Forceu/barcodebuddy#105]
First, thank you for creating this very useful app. Grocy is much more useable, thanks to your effort.

Could you add support to the Grocy 3.0.0 feature "[Prefill purchase data by barcodes](https://github.com/grocy/grocy/releases/tag/v3.0.0)"? 
This is such a critical feature for my workflow and is stopping me from switching to barcodebuddy entirely.

Thanks in advance :)

**Comment by Forceu** [comment]
I will add it to my todo list. At the moment you can use Barcode Buddys internal Quantity-Per-Barcode feature: https://barcodebuddy-documentation.readthedocs.io/en/latest/usage.html#quantities

**Comment by skanur** [comment]
Thanks! I will try the suggested workflow for now.

**Comment by Forceu** [comment]
Added in c1ea4d3. I might actually replace the local quantity feature with only querying Grocy.

**Comment by skanur** [comment]
Thanks! Waiting to try this feature out in your next release.

**Comment by Forceu** [comment]
I did completely replace the internal quantity handling with Grocys barcode management in 3e6a380707e72e6936d1ff86288f6eb43086b800.

If you are using docker, you can try it out with the image f0rc3/barcodebuddy-docker:latest-dev

**Comment by skanur** [comment]
Thanks. I did try the latest development version. Purchase + Consume using barcodes work perfectly fine. I also noticed that the Quantities tab is updated with quantities assigned to barcodes in grocy. Awesome. Many thanks!!

But I noticed that using BBUDDY-O or BBUDDY-CS on barcodes opens/consumes by 1. Is this expected?
