### ISSUE TITLE
Is it possible to drop dependencies to google?

### ISSUE THREAD

**Issue by budda85** [Forceu/barcodebuddy#106]
For privacy protection it would be nicer if you can drop the dependencies to google.
I see Barcodebuddy is connecting to google to load the font.
Maybe we can load the font locally, so no connection to google is necessary.
I can help to download the fonts, but there are over 50 species in the font. Are they all needed?

**Comment by Forceu** [comment]
Thanks, yes that would be a good idea. I will look into it in the next days, most of the fonts are not needed.

**Comment by Forceu** [comment]
Fixed in aeb1858ce71e7adc80a8f514af0ca26f6436ebb0
