### ISSUE TITLE
Offer option to set UID and GID for the user running barecodebuddy in the Docker container

### ISSUE THREAD

**Issue by wechsler42** [Forceu/barcodebuddy#109]
Hi there,
first of all thank you very much for sharing barecode buddy with us! I use it in a Docker environment together with the Android app.
I would like to suggest to offer a possibility to set the UID and the GID for the user used to run barecode buddy in the docker container.
I work with this docker-compose file, user 1002 is a designated docker user on my docker host:

version: '2.1'
services:
    barcodebuddy-docker:
        volumes:
            - 'path_to_my_directory_on_docker_host:/config'
        ports:
            - '8082:80'
            - '9443:443'
        image: 'f0rc3/barcodebuddy-docker:v1.5.1.0'
        user: "1002:100"
        restart: unless-stopped

When I use a user other than root to run barecode buddy in the container than I receive this error: "s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied".

**Comment by Forceu** [comment]
I moved this issue to https://github.com/Forceu/barcodebuddy-docker/issues/11 as it is related to the docker image
