### ISSUE TITLE
Feature request : Add products database/barcodes from Codecheck.info

### ISSUE THREAD

**Issue by Yokiie** [Forceu/barcodebuddy#112]
Hi, 
I'm from a European country and most of the products sold in my country that I scan with barcode buddy are not recognized, because they're not in the OpenFoodFacts database (or any currently supported databases) sadly.
However one of the largest european food database [codecheck.info ](https://www.codecheck.info/)  has all the products I use on the daily (and 2 million products), luckily they have [an API available on request](https://codecheck-app.com/business/api/)  so I think it would be cool for barcodebuddy to implement their database as well, I think many european users would love that feature :) 

This is basically the only thing keeping me from fully enjoying barcodebuddy/Grocy for now. Sadly I'm not a good enough programmer to contribute myself to this new feature but let me know if I can help :)

**Comment by Forceu** [comment]
Thanks, I know that they have a rather extensive collection of barcodes, unfortunately the API is not free, therefore out of scope for this project :/
