### ISSUE TITLE
Redis connection with password use

### ISSUE THREAD

**Issue by Goeste** [Forceu/barcodebuddy#114]
Hi,
I wanted to ask if it is somehow possibe to add a password to the redis settings because I'm already using redis with a password for another nextcloud instance (both running as docker).

Best regards, goeste

**Comment by Forceu** [comment]
Sorry I couldn't get around of replying yet, I will probably have some time in the next days to implement this feature.

**Comment by Forceu** [comment]
Added in 3f3a6e2203274cc2b4a53ae6a8f49ecc1d334950
