### ISSUE TITLE
Consuming only integer amount

### ISSUE THREAD

**Issue by bell0x07** [Forceu/barcodebuddy#115]
Grocy supports floats up to 4 decimal points, sometimes I am using 1 Package as a unit, and I want to consume 0.1 of package of something, in that scenario Barcode buddy consumes either 1 package or 0 packages, even though the quick consume amount in grocy is specified as 0.1.

Steps to reproduce:
Add a product in grocy with quick consume amount 0.1
Consume using barcode buddy
check the barcode buddy log to see what amount has been consumed.

I understand not all users would like that behaviour, perhaps a good option would be to add global switch that would change this behaviour.

**Comment by Forceu** [comment]
Thanks, I will look into it in the coming weeks.

**Comment by Forceu** [comment]
Fixed by #166
