### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by realbuz** [Forceu/barcodebuddy#116]
I've just started looking at grocy and barcodebuddy.  The goal I'm trying to achieve is to have a raspberry pi sitting in the food storage room with only a barcode scanner attached.  It would be great to have a way to run barcodebuddy in a headless fashion only to substract inventory when I send the kids to get something in there.  I'm going to try and modify a python script that I've found (https://www.instructables.com/USB-Barcode-Scanner-Raspberry-Pi/) to make api calls, but I'm not a programmer.  Having an integrated way to do this would be awesome.

**Comment by realbuz** [comment]
just found the grabinput in example. seems like this will allow me to do what I want.

**Comment by Forceu** [comment]
Yes, that is exactly what it is for, great to hear you have some use for it :)
