### ISSUE TITLE
extensible feedback system

### ISSUE THREAD

**Issue by diplix** [Forceu/barcodebuddy#12]
i’m using barcode buddy with a phone-barcode-scanner (calling barcodebuddy via a http request) and hacked/extended the `api.inc.php` and `processing.inc.php` files to add feedback for certain actions. in my case i want to let my personal assistant ([snips](https://snips.ai)) say „changed mode to add“, „cucumber added“, „water consumed“.

i wrote a function `function snipsSay($text) {}` that i call in `processNewBarcode`:
```
        saveLog("Set state to consume", true);
        sendWebsocketMessage("Set state to consume", $websocketEnabled);
        snipsSay('Bestand Verbrauch');
```
it’s not to hard to add my code after each release of barcodebuddy, but i was wondering if there could be a more general approach for that. you just extended `processing.inc.php` for websocket messages, someone else might like to send a http request to a buzzer or other text to speech systems.

any idea for a general approach or extensibility without making to much of a fuzz?

**Comment by Forceu** [comment]
Thank you for your feedback, that does sound like a good idea! I guess implementing aa plugin system would be a good idea, I'll have a look at it on Tuesday latest :)

**Comment by diplix** [comment]
no hurry neccessary. i just remembered, while i was implementing a snips skill for consuming and adding products (i.e. by saying „i consumed 2 eggs“) i implemented feedback for anonouncing the stock amount. but looking up the stock amount could then be covered or extended with a plugin system.

**Comment by Forceu** [comment]
Yes, stock lookup is already on my todo list and once it's implemented your use case should be very easy to add as well

**Comment by Forceu** [comment]
Plugin support is now available in c62bdf3290666db77e76ce1b16c7a475d34d7def

**Comment by diplix** [comment]
thanks, i reworked my text-to-speech-feedback (a bit) and the integration is a bit cleaner now. i have a plugin file with a class that handles text to speech and i use `EventReceiver.php` to send the log entry to the tts class.
since all the log entries are english and my voice assistant only talks german i hacked german translations into `processing.inc.php`. that works well for me, while it’s not very clean.

to do a cleaner version i would need either the barcode variable, or better `$productInfo`  to construct sentences to be spoken. just anouncing events is not very helpful.
the other path would be to allow customising and/or translating the log entries.

just an example what i did in processing.inc.php:

```
    switch ($state) {
        case STATE_CONSUME:
            consumeProduct($productInfo["id"], 1, false);
            //outputLog("Product found. Consuming 1 " . $productInfo["unit"] . " of " . $productInfo["name"] . ". Barcode: " . $barcode, EVENT_TYPE_ADD_UNKNOWN_BARCODE, false, $websocketEnabled, 0, "Consuming 1 " . $productInfo["unit"] . " of " . $productInfo["name"]);
            outputLog(
                "1 " . $productInfo["unit"] . " " . $productInfo["name"] . " verbraucht.
                Neuer Bestand: ".$productInfo["stockAmount"]. " " . ($productInfo["stockAmount"] == 1 ? $productInfo["unit"] : $productInfo["units"]), 
                EVENT_TYPE_ADD_UNKNOWN_BARCODE, false, $websocketEnabled, 0, 
                "1 " . $productInfo["unit"] . " " . $productInfo["name"] . " verbraucht."
            );
            break;
```

all this might change in the next couple of days (or weeks), when i receive a stationary barcode scanner which i might extent with a screen, then using your websocket screen path instead of tts feedback.

**Comment by Forceu** [comment]
For now this is not a high priority, as I would like to add other features first before adding very extensive plugin support. However feel free to add a Pull Request if it is working for you :)
