### ISSUE TITLE
Floating point quantities are truncated after decimal

### ISSUE THREAD

**Issue by skanur** [Forceu/barcodebuddy#122]
I noticed quantities with floating point values are truncated to contain only decimal places, when adding/consuming products. I suspect if affects other modes too, but I haven't tested it.

The use case for floating point quantities arise in day-to-day use when stock unit is continuous number like liters and is different than purchase unit e.g. Liters as stock unit and purchased in amounts of 0.5 L.

Milliliters to Liter conversion via barcode is unfortunately broken in grocy as of now (see https://github.com/grocy/grocy/issues/1264#issue-782635751), so I have to use decimal quantities for now. Is it possible to fix it?

Thanks in advance :)

**Comment by Forceu** [comment]
Fixed by #166
