### ISSUE TITLE
Barcode buddy and Grocy running on same ports

### ISSUE THREAD

**Issue by aaronmartin1651** [Forceu/barcodebuddy#124]
I installed grocy and barcodebuddy installed on baremetal.  Everthing went fine, grocy launched as expected gut after installing barcodebuddy and configuring nginx I get "Failed to start A high performance web server and a reverse proxy server" which typically means two sites listening on the same port.  Sure enough, both grocy and barcodebuddy listen on port 80.  I changed barcode buddy nginx config to listen on 8080 just to see if it would launch and attempted to restart nginx services but same message.  I think this is likely just something missing from the instructions rather than a bug but I combed through the installation guide and can't find anything I might have missed.  What could be the cause of this?

**Comment by Forceu** [comment]
Sorry for the late reply. Are you still having this issue? If yes, please comment below.
