### ISSUE TITLE
Feature Request: Separate Fields for API URL and Public-Facing URL in BarcodeBuddy Settings

### ISSUE THREAD

**Issue by SalmonSays** [Forceu/barcodebuddy#129]
I run all my docker containers behind Traefik as a reverse proxy, and Traefik-Forward-Auth (https://hub.docker.com/r/thomseddon/traefik-forward-auth) as a forward authentication service. This allows me to check users, myself included, against a list of allowed gmail accounts (or other authentication service) before granting a cookie that serves as a "password" for access to all of my sites.

When connecting to BarcodeBuddy to Grocy, rather than use my public "https://grocy.example.com" address which is certed and forward-authenticated for security I pass it along the docker backend over "http://grocy" which resolves perfectly. The problem is when adding new products from a barcode or selecting Grocy from the upper right corner of the main BarcodeBuddy screen, it passes the Grocy API URL (http://grocy) to the user which fails immediately because they are meant to use the forward authenticated variant.

I'm hoping you might be receptive to implementing an alternate, optional URL config field in settings that separates the application connection to Grocy from the address users are directed to. Services like Heimdall handle them in this way:

![JAjBrOg](https://user-images.githubusercontent.com/11697389/113953344-381e2b80-97dd-11eb-9a03-1cf2522fab7a.png)

I recognize as a consumer and not a high-stakes fortune 500 company that it's not the end of the world to disable forward-auth on Grocy and direct everyone at the same certed address, but keeping forward-auth adds a best-practices layer of security that I'd prefer not to have to do without and I readily recommend for others.

**Comment by PsikoBlock** [comment]
Have you tried setting `EXTERNAL_GROCY_URL` in config.php? That seems like it's exactly what you need.

**Comment by SalmonSays** [comment]
I haven't- that sounds promising but I can't find that particular setting in my config.php. I'm on Version 3.0.1
(Released on 2021-01-05 6 months ago) based on the linuxserver docker container and even after just recreating the config.php it isn't appearing.

**Comment by Forceu** [comment]
You need to edit barcode buddy's config, you are currently looking at grocys `config.php`.

Have a look at https://barcodebuddy-documentation.readthedocs.io/en/latest/advanced.html#advanced-usage-and-configuration where to locate Barcode Buddy's `config.php` and how to edit it.

**Comment by SalmonSays** [comment]
That makes total sense, to be honest I left this issue alone for a while and forgot some of the details. I just tried it out and everything appears to be working, so thanks very much for the assistance!
