### ISSUE TITLE
websockets: Disconnected SSL

### ISSUE THREAD

**Issue by ChadOhman** [Forceu/barcodebuddy#13]
Hello,
I'm setting up grocy with barcodebuddy on Rancher. I have a L7 Ingress load balancer set up to pipe port 476321 to the Docker container from external port 30502, however I'm still getting a connection refused error.
Is it possible to set up TLS over WS with barcodebuddy to get around having to serve the page over HTTPS?
Thanks!

**Comment by Forceu** [comment]
Hi,
yes that is indeed possible. Go to settings and enable "Use SSL Proxy". Then enter a URL, eg. "wss://yourserver.com/screen". You can find an example for NGINX here: https://github.com/Forceu/barcodebuddy/blob/master/example/nginxConfiguration.conf Simply remove the comments at the "location /screen" section

**Comment by ChadOhman** [comment]
Hey thanks for the reply, it must be something to do with my configuration. Rancher uses NGINX as a reverse proxy but doesn't expose its configuration for our purposes. So I'll have to play with it a little more.
Cheers
