### ISSUE TITLE
Feature Request: Grocy Extension

### ISSUE THREAD

**Issue by jamesgeddes** [Forceu/barcodebuddy#130]
Extension for Grocy that allows users to access all the features of Barcodebuddy from within Grocy.

Originally logged as grocy/grocy#1454

**Comment by Forceu** [comment]
Unfortunately this is not in the scope of this project. Its purpose is to be standalone

**Comment by jamesgeddes** [comment]
That's too bad. It would be awesome if it could all work in one place.
