### ISSUE TITLE
API request: Allow /action/scan through GET and params in URL

### ISSUE THREAD

**Issue by azapater** [Forceu/barcodebuddy#134]
Here's an idea I've had in my quest to simplify the use of grocy as much as possible:

I love barcodebuddy and the app for android is great, but in my household there are users with iPhones which makes the whole experience a bit more complicated. My idea is to print QR codes with URLs and stick them next to the products we don't often need to add to the shopping list. That would give us the possibility to add them on demand quickly from any device (pretty much like the amazon dash buttons worked) just scanning the QR code. 

The API you provide is great, but following the good rules of APIs the /action/scan is a POST, which makes it impossible to implement that API call in a QR code. Would it be possible to give the same functionality as the POST method but using a GET one? It'd also be great if it could accept the same params in the URL itself to give more flexibility to create different QR behaviours (I'm even thinking a coloured QR system for adding to the shopping list, consume products etc...). 

Thanks for your hard work!

**Comment by MrJohnZoidberg** [comment]
This is already possible: https://barcodebuddy-documentation.readthedocs.io/en/latest/advanced.html#non-standard-api-action-scan
