### ISSUE TITLE
Feature request: Set default scan mode

### ISSUE THREAD

**Issue by freakshock88** [Forceu/barcodebuddy#135]
I use barcode buddy only with the add to shopping list mode. 

I would like to be able to set this mode as a default mode, without having to scan to change a barcode to change the mode each time I want to build a new shopping list. Could this be added please? 

A easier workaround would be perhaps to disable the 'revert state to consume' setting or be able to set it to 0. I tried this but it still reverts to consume mode after a short while.
However even if this workaround would work this would mean that I have to change the scan mode each time Barcode Buddy restarts. I would prefer to be able to set the default mode to shopping list without ever having to set it again. 

Please let me know if my feature request is clear :)

**Comment by Forceu** [comment]
Thank you for your input and sorry for the late reply! Added in 0a4097c0b45781bb1290968f489446a9e26f528d, if `Revert_TIme` is set to 0, it will disable reverting back.
