### ISSUE TITLE
Feature request: Use last price from grocy when purchase

### ISSUE THREAD

**Issue by QGgWW2WhH** [Forceu/barcodebuddy#137]

**Comment by Forceu** [comment]
Normally the last price should be used by Grocy by default, unless Grocy changed this behaviour.

**Comment by QGgWW2WhH** [comment]
Thanks for your reply!

I checked all settings once again - does not work:
 - check if product has latest price > 0
 - check if product has default shop != null
 - set barcode buddy on purchase
 - scan barcode
 - check if barcode buddy has picked up code
 - check inventory in grocy
 - not expected result: new stock with price = 0 and shop = null - I was expecting the latest price and the default shop?

Can you reproduce this behaviour? 
Thank you, 
BR
