### ISSUE TITLE
Bug: Purchasing 0,1 Kilogram

### ISSUE THREAD

**Issue by QGgWW2WhH** [Forceu/barcodebuddy#138]
Hello, 

This may be linked to: https://github.com/Forceu/barcodebuddy/issues/115

 - I scan a barcode
 - it looks up the product in grocy
 - it takes the amount: 0,1 Kilograms
 - BUG: it tries to add 0 Kilograms to the stock and does not show an error

Could we please allow for float quantities? 

A workaround would certainly be to amend all barcodes and convert them to grams instead of kg. 

Great tool by the way!

**Comment by michaelschramel** [comment]
> A workaround would certainly be to amend all barcodes and convert them to grams instead of kg.
unfortunately this does not work - you have to delete the product and recreate it with g instead of kg as base unit

**Comment by Forceu** [comment]
At the moment only natural numbers (as in no decimal / fractions) can be processed. I will probably change that in the future.

**Comment by Forceu** [comment]
Fixed by #166
