### ISSUE TITLE
Bug: Error on addBarcode - "UNIQUE constraint failed: product_barcodes.barcode"

### ISSUE THREAD

**Issue by austinsellers** [Forceu/barcodebuddy#140]
Having just installed barcodebuddy in a docker container and successfully connecting it to Grocy I scanned my first item. I went to the UI and associated it with an item in Grocy.

After clicking the "Add" button I saw an error in  "Processed Barcodes" as follows:
```Invalid JSON: Could not set Grocy barcode SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: product_barcodes.barcode Please check your URL and API key in the settings menu!```

The error code indicates that this is an issue thrown by [addBarcode](https://github.com/Forceu/barcodebuddy/blob/master/incl/api.inc.php#L450). 

There is also [issue #1546 in the grocy repo](https://github.com/grocy/grocy/issues/1546) with the same error code in their issue tracker. 

That issue has been closed stating _"Product barcodes are enforced to be unique across products since v3.1.0, during the migration, for any duplicates, only the latest added barcode will be kept"_. 
That change is also listed in the [changelog for v3.1.0](https://github.com/grocy/grocy/blob/master/changelog/62_3.1.0_2021-07-16.md#stock-improvementsfixes) which is currently the latest release and was released on July 16, 2021.

**Comment by Forceu** [comment]
Thanks, in that case this is a problem on Grocys side. Apparently this will be fixed in the next Grocy release. Alternatively you can remove any duplicate barcodes on your Grocy instance or replace the sql file mentioned in https://github.com/grocy/grocy/issues/1546
