### ISSUE TITLE
Screen: Toggle mute fails

### ISSUE THREAD

**Issue by MrJohnZoidberg** [Forceu/barcodebuddy#142]
Hi, maybe this is something on my side only:

The mute/unmute button on the screen page cannot be toggled, in the browser console there is an error:

`getElementById("muteimg") returns null`

from this line:
https://github.com/Forceu/barcodebuddy/blob/c2dd8094d25cd1852ea056ad6fc0a9b10eaaf60e/screen.php#L336

I had to append `id="muteimg"` to this line and all was fine:
https://github.com/Forceu/barcodebuddy/blob/c2dd8094d25cd1852ea056ad6fc0a9b10eaaf60e/screen.php#L261

Is there something wrong on my side or is this a bug?

**Comment by Forceu** [comment]
Thanks a lot! For some reason I removed the id in 57dba901ffda23b89fe6d2beee0e548eeeef22db
