### ISSUE TITLE
Incompatible with PHP8

### ISSUE THREAD

**Issue by Shredder5262** [Forceu/barcodebuddy#145]
I have managed to struggle through getting nginx installed, grocy installed and set up, and now barcode buddy installed...now i am at the stage of trying to get the mobile app connected to barcodebuddy. I've tried following the documentation and that doesn't seem to be working for me. 
I see this error in barcode buddy so i think that has something to do with it, but the documentation for me is not clear enough on how to fix it 
Websocket Server Status

Websocket server is not running! Unable to connect to websocket server: Connection refused (111)

When i try to scan the QR code from the app i get this error message 

could not conect to the server!invalid UIRL or incorrect response . Please make sure that the URL is correct and URL rewriting is enabled. 

I've tried the url that is being entered into a browser and it does work in a browser...so i'm not sure where to go from here. 
happy to provide logs or anything needed to assist...i'm not even sure what to provide at this point though....
here is what i have in the barcode buddy nginx config 

server {

       listen 81;
        listen [::]:81;
        server_name _;
        root /var/www/html/barcodebuddy;
        index index.html index.htm index.nginx-debian.html index.php;
        location / {
                try_files $uri /index.php;
        }
        client_max_body_size 100M;

        client_body_buffer_size 128k;

        location ~ \.php$ {

                include snippets/fastcgi-php.conf;

                fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
        }

}

**Comment by Shredder5262** [comment]
thought this might be relevent also, this happens when i try the instruction 
"Navigate to your installation folder and execute php wsserver.php to start the server."

root@Linuxbox:/var/www/html/barcodebuddy# php wsserver.php 
PHP Warning:  Private methods cannot be final as they are never overridden by other classes in /var/www/html/barcodebuddy/incl/websocket/php-websocket/src/Application/Application.php on line 19
PHP Fatal error:  Uncaught TypeError: ob_implicit_flush(): Argument #1 ($enable) must be of type bool, int given in /var/www/html/barcodebuddy/incl/websocket/php-websocket/src/Socket.php:26
Stack trace:
#0 /var/www/html/barcodebuddy/incl/websocket/php-websocket/src/Socket.php(26): ob_implicit_flush()
#1 /var/www/html/barcodebuddy/incl/websocket/php-websocket/src/Server.php(69): Bloatless\WebSocket\Socket->__construct()
#2 /var/www/html/barcodebuddy/wsserver.php(50): Bloatless\WebSocket\Server->__construct()
#3 {main}
  thrown in /var/www/html/barcodebuddy/incl/websocket/php-websocket/src/Socket.php on line 26

**Comment by Shredder5262** [comment]
so no support for this then?

**Comment by Forceu** [comment]
> so no support for this then?

This is not a commercial project and I am doing this in my free time for free. I find it a bit amusing that you reply with that after less than 24 hours. Seems to be a problem related to PHP8, I will look into it once I have some time.

**Comment by Forceu** [comment]
Fixed in 09e54b9564798a9f78958a93f1806c64d9fe5ac3. Please try again with the current commit and let me know in case it still does not work.
