### ISSUE TITLE
URL Call does not respect BarcodeBuddy State

### ISSUE THREAD

**Issue by martydingo** [Forceu/barcodebuddy#15]
I'm trying to add stock, I've edited the example python script slightly to make URL calls instead of trying to run PHP directly, since my instance of nginx is in a docker container and isn't directly available. I can't just run the python script in the docker image, as my barcode scanner is plugged into a rPi and I'd need to pass through USB. 

I've added the line, requests.get('http://URLHERE/index.php?add='+data), and commented out the os.system call. 

Unfortunately, when I put Barcode Buddy into Purchase Mode, when I scan a barcode following this it still consumes stock. I've tested using a os.system call to docker, which then runs a call to the php binary to process the barcode, which works correctly. 

Not working with URL Call using requests:
2019-10-17 15:59:18: Product found. Consuming 1 Piece of San Pellegrino Aranciata Sweet Red Orange. Barcode: 8002270706523
2019-10-17 15:59:14: Set state to Purchase

Working with os.system
2019-10-17 16:03:19: Product found. Adding  1 Piece of San Pellegrino Aranciata Sweet Red Orange. Barcode: 8002270706523 [WARNING]: No default best before date set!
2019-10-17 16:02:30: Set state to Purchase

It'd be really handy if Barcode Buddy recognised what state it was in, when adding a barcode via the URL.

**Comment by martydingo** [comment]
Unfortunately using subprocess or os.system results in a 10 second lag, which isn't very good, but the HTTP GET is pretty much instant, hence the question!

**Comment by Forceu** [comment]
Hm that is very weird, I just tried it and could not reproduce the problem.
I could image that it is a timezone problem, if you add a barcode from the UI by clicking on the "Add barcode" button, does the same problem occur?

**Comment by Forceu** [comment]
Can you please clone the github repo with the current commit 4377595a7b551f062b1f6b9f1134210a549d5412 and let me know if it is working now?

**Comment by martydingo** [comment]
I've cloned the repo and installed it that way.

And that did the trick! 

2019-10-17 19:22:08: Product found. Adding  1 Piece of Double Drip Coil Sauce Lemon Sherbet 50ml. Barcode: 5060537825014
2019-10-17 19:21:51: Set state to Purchase

Thanks very much for that.

**Comment by Forceu** [comment]
Great to hear, thank you for your feedback! :)
