### ISSUE TITLE
High CPU load with 1.8.1.0

### ISSUE THREAD

**Issue by ict** [Forceu/barcodebuddy#150]
Since Watchtower updated my container this morning, wsserver.php is consuming a constant 15% CPU while being completely idle.
Recreating the container did not bring any improvement.

Reverting to the previous version fixes the issue back to 0.1%.

Let me know if I can help troubleshoot this issue.

**Comment by Forceu** [comment]
Thanks a lot for letting me know! Apparently the PHP documentation is incorrect regarding one function used, which in the end caused very high CPU load. Fixed in 1477a67e90d75c50400bcc0bdcac24db5272cc6 and the new release.
