### ISSUE TITLE
grabinput.sh in Docker wrongly finds "custom barcode"

### ISSUE THREAD

**Issue by ict** [Forceu/barcodebuddy#153]
Since upgrading to the new release, the Docker container (with `ATTACH_BARCODESCANNER` enabled) fails to send any barcode that is not strictly numeric to BarcodeBuddy. It only prints "Custom barcode scanned":
![grafik](https://user-images.githubusercontent.com/488575/129788384-0dcc780f-0855-4405-a7ac-c056b9b2d7aa.png)

I tried setting the environment variable `SPECIAL_BARCODE` to some unused value, but this did not remediate the situation.

Early edit:
I think the use of `-eq` in the script is wrong here. `man test` says `-eq` should be used for numbers. Changing the script to use `==` instead fixes the issue.

**Comment by Forceu** [comment]
Thanks a lot! I fixed this in c9996d0e19e416a8bb6de03a2e3d614a729cf050, can you please try with the `latest-dev` image if it is working now?

**Comment by ict** [comment]
Fast as always :) Sure, I’ll test tomorrow and report back.

**Comment by ict** [comment]
Yes, the `latest-dev` image works again without any hacks.
