### ISSUE TITLE
Unable to connect to API: Could not connect to server. API Keys not showing up in the 9192 port end point

### ISSUE THREAD

**Issue by RobertWaiteREPAY** [Forceu/barcodebuddy#154]
Hello, 
I've been trying to get a barcode buddy to wired up with the home assistant. I have the network section of the grocy configuration set to port 9192, SSL is turned off. I can successfully get to what seems to be an instance of grocy and http://homeassistant.local:9192/api successfully gets me to the API browser. On attempting to wire up Barcode Buddy setup with http://myHomeAssistant:9192/api/ I get the message of Unable to connect to API: Could not connect to server. What is unusual about getting into Grocy via the 9192 port is I don't see any records anywhere. There are API keys but they only show up when I'm on the Home Assistant screen(not the 9129 port). I suspect not being able to see those records when using the 9192 port is part of the problem.  
This is a screencast depicting the issue.

https://www.dropbox.com/s/y6fk1l2t03njz03/Screen%20Cast%20demoing%20the%20Grocy%20Barcode%20buddy%20issue%20%202021-08-18_20-14-34.mp4?dl=0

Any insight on what I can try?
Thanks
Robert

**Comment by ict** [comment]
Just a guess, but maybe those mDNS hostnames cannot be resolved inside the docker containers themselves. Did you try using the IP address or the internal container name instead?

**Comment by Forceu** [comment]
Yes, that seems to be an issue with your docker setup. Please enter the IP address of the grocy container or a hostname that can be resolved to said IP
