### ISSUE TITLE
BB not recognizing custom barcodes from remote grabInput.sh 

### ISSUE THREAD

**Issue by danukefl** [Forceu/barcodebuddy#157]
Looks to be related to #153 but on the latest tag (1.8.1.3), I still experience the same issue where custom barcodes are not recognized by BB. 

Setup:
BT Scanner connected to RPI with grabInput.sh connected to Docker BB container and is connected to Grocy also in Docker.

```[ScannerConnection] Waiting for scanner input
[ScannerConnection] Received: BBUDDY-P
Custom barcode scanned
[ScannerConnection] Received: 085239042939
/home/pi/grabInput.sh: line 145: [[: 085239042939: value too great for base (error token is "085239042939")
{"data":{"result":"Product found. None in stock, not consuming: Almond Milk [085239042939]"},"result":{"result":"OK","http_code":200}}```

**Comment by Forceu** [comment]
Hm interesting. Can you confirm that your `/home/pi/grabInput.sh` file is the one from the current release?

**Comment by danukefl** [comment]
Add another one to user errors, I had updated the script on the RPI but not the Ansible playbook that then overwrote it when updating everything else. Thanks for the quick response.
