### ISSUE TITLE
Screen Mode Inventory fails to parse Json if location is included

### ISSUE THREAD

**Issue by budda85** [Forceu/barcodebuddy#160]
When I am in screen mode and I want to check my inventory, I do not see any products that are in stock.
I see "Set state to Inventory" and thats it. In the log in the overview, i can see everything.
Products which are not yet known to Grocy are displayed. When consuming and purchasing everything is displayed correctly.
I am on version 1.8.1.4 with docker.

Edit: Add Screenshots
![Bildschirmfoto 2021-10-12 um 21 31 13](https://user-images.githubusercontent.com/20152200/137017824-7f7c90e4-d3cb-42cb-b9c2-7139210200ac.png)
![Bildschirmfoto 2021-10-12 um 21 31 42](https://user-images.githubusercontent.com/20152200/137017829-24dd6c5b-085c-48ea-956b-c35d44ebc45f.png)

**Comment by budda85** [comment]
No one else with this problem??

**Comment by Forceu** [comment]
Sorry, I missed that issue, I will look into it tomorrow!

**Comment by Forceu** [comment]
Fixed in 7f32286
