### ISSUE TITLE
Enhancement: Get the last Log-Entry via API / Add MQTT support

### ISSUE THREAD

**Issue by fhold** [Forceu/barcodebuddy#164]
In order to be sure if the last action was correct it would be great if one could fetch the last log entry via the api, so that one could send a message via e.g. telegram. That would tell me if everything went right and i would not have to check in the web ui.

**Comment by fhold** [comment]
Thinking about this again it would be even easier if there would be an mqtt integration where the log-entries are pushed to a topic. Is there anything planned for the future? Or do you have any ideas how to achieve this without coding?

**Comment by Forceu** [comment]
A mqqt client would be out of scope for this project (at least for now). You can however write your own plugin, you simply need to extend the example, which receives every new log entry https://barcodebuddy-documentation.readthedocs.io/en/latest/advanced.html#plugins

**Comment by fhold** [comment]
thanks for the quick reply. I understand that implementing a mqtt-client is out of scope. As I'm not firm in coding, how about using an existing library and using that to send the information. How would one import such a library when using the plugin script?

**Comment by Forceu** [comment]
The function `pluginEventReceiver_processEvent` is called on every event, with `$log` being a string containing the latest log line. You could use a library like https://github.com/php-mqtt/client to send the data.

To be honest, mqtt broadcast would be a nice feature, I might look into it at some point.

**Comment by fhold** [comment]
sorry for beeing such a noob. But how would i use the composer command in order to import that library (I already found that one and also a tutorial how to send messages)?

**Comment by Forceu** [comment]
Sorry, I would love to help you out, unfortunately I have a lot to do this month. There are a lot of tutorials available online however on how to use composer

**Comment by PiAir** [comment]
@fhold I thought it was a nice feature request, so I used it for my first attempt to build a barcodebuddy plugin.
You can [find it here](https://github.com/PiAir/bbuddy-plugin-MQTT)

**Comment by Forceu** [comment]
Looks awesome, thanks a lot for your work! If there is an easy way to merge it feel free to do so :)

**Comment by fhold** [comment]
@PiAir wow awesome. Will try it out on the weekend. I will first have to move away from the HA addon. I then plan to make a mqtt sensor which shows the last log entry and show that on my wall-mounted tablet, so it will look neat and clean.

**Comment by PiAir** [comment]
I did the same, The ![second screenshot](https://raw.githubusercontent.com/PiAir/bbuddy-plugin-MQTT/main/resources/screenshot_2.png) uses a custom card in Home Assistant. At the moment I can only get access to a text string from the log (that is the way barcode buddy works for now), I was hoping to also get the barcode and/or the image, but that is still on my wish list.

**Comment by PiAir** [comment]
> Looks awesome, thanks a lot for your work! If there is an easy way to merge it feel free to do so :)

You're welcome. I designed it as a plugin for now. As an integrated part I would probably add the logic in different places in your code. So for now, this might be best/good enough. :-)
Also, this allows others to choose if they want to add it or not.
