### ISSUE TITLE
bug: /menu/quantities.php is blank page

### ISSUE THREAD

**Issue by QGgWW2WhH** [Forceu/barcodebuddy#165]
v1 8 1 4 
tried to create new blank db
all other features work

/menu/quantities.php takes long time to load and then is a blank page

**Comment by Forceu** [comment]
Thanks for the bug report! I just tried it with an existing and a new instance (and also existing / new grocy instance), however I am unable to reproduce the problem. Do you have any error messages or output to your webserver logs?
