### ISSUE TITLE
Status Unavailable  after a few Hours

### ISSUE THREAD

**Issue by mattpitts74** [Forceu/barcodebuddy#168]
I have recently installed the latest version Barcode Buddy on docker running on an RPI4.  I have Grocy running as an addon in Home assistant running on another computer on my network.  

Everything is working as expected, except when I come back to the RPI running Barcode Buddy a few hours later I notice that the status on the "Screen" page has been unavailable.  So I have to exit that screen and re-enter that screen for it to reconnect.  

Is this normal behavior?  or is this a Bug?

**Comment by Forceu** [comment]
Thanks a lot for the bug report and please excuse the late reply. I will look into it.

**Comment by Forceu** [comment]
Fixed in 34cd06b
