### ISSUE TITLE
New Products are not Created

### ISSUE THREAD

**Issue by mr-gosh** [Forceu/barcodebuddy#169]
Hi I set up Grocy and Barcodebuddy via docker behind a traefik2 proxy and the API calls are working and I can add products that are present in Grocy via Barcodebuddy.
BUT
Products that are not in Grocy but that are found via federation or lookup can not be created in Grocy.
I understood the interface this way:
- Name shows me what's was found via lookup
- new products stay on drop-down "= none ="
- select the right tags
- click on "create product"
But than nothing happens... What did miss here?

Grocy and Barcodebuddy are on latest docker image version.

THX for the hints...

**Comment by Forceu** [comment]
If you click on Create Product, a new tab should be opened, containing grocys Create New Product page. Maybe it has been blocked by a popup blocker?

Once the product has been created, it is automatically selected in the drop down list. You can then select tags if available. By clicking on either Add or Consume you then associate the barcode with the new product.

**Comment by mr-gosh** [comment]
OK thx.
This tab did not open cause I already had a Grocy tab open.
Since I closed that one it works.

THX for the help
