### ISSUE TITLE
BB Screen not receiving barcode from BT scanner

### ISSUE THREAD

**Issue by ChadOhman** [Forceu/barcodebuddy#17]
Hi there,

BB Screen is Connected however stays on "Waiting for barcode..." when I scan something with my bluetooth scanner in HID (keyboard input) mode on my Raspberry Pi running Rasbian and Chromium.
The scanner is working correctly as I can choose "Add barcode" on the main screen and it will input the barcodes into the resulting text box.

Am I doing something wrong? Thanks..
![2019-11-10 00_34_57-10 0 20 2 (raspberrypi) - VNC Viewer](https://user-images.githubusercontent.com/2351/68540602-fd973180-0351-11ea-876f-bd056a10ec57.png)
![2019-11-10 00_34_37-10 0 20 2 (raspberrypi) - VNC Viewer](https://user-images.githubusercontent.com/2351/68540603-fd973180-0351-11ea-8c3f-be5708fb304e.png)

**Comment by Forceu** [comment]
I assume you downloaded the latest release instead of the current commit? It was originally a feature that no message was sent when a barcode was inserted manually, but I reverted it in one of the last commits

**Comment by ChadOhman** [comment]
Hi, yes, I'm running the latest release. Should I give it a try with the last commit?

**Comment by Forceu** [comment]
Yes, I would recommend that for your purpose. As it is saying "Connected", the websockets are working fine.

**Comment by ChadOhman** [comment]
Hi, I pulled the latest master and still have the same problem. The scanner outputs to the text field fine but not to the screen. Thanks

**Comment by Forceu** [comment]
If you are using the manual input box, you would need to click on "Add" after scanning the barcode(s).
A better option would be to use this script, which redirects the barcode input directly to Barcode Buddy

**Comment by ChadOhman** [comment]
I'll give the script a try and report back. Thanks.

**Comment by ChadOhman** [comment]
Alright, script is running -  no update to the screen. Am I missing something?

![2019-11-10 02_37_07-10 0 20 2 (raspberrypi) - VNC Viewer](https://user-images.githubusercontent.com/2351/68541940-0e9c6e80-0363-11ea-8cde-7d334fb072d4.png)

**Comment by Forceu** [comment]
Please check if you have screen installed (sudo apt-get install screen).

Also if you execute `php /your/path/index.php 123456`, the barcode 123456 should be looked up and sent as a websocket broadcast.

**Comment by ChadOhman** [comment]
Okay, so `php index.php 123456` works and is sent as a websocket broadcast. The grabInput.py script still isn't sending data to the Screen page. I've tried pairing the barcode scanner to my iPhone and on Safari and Chrome neither are getting the input from the scanner. I'm not sure what I'm missing.

**Comment by Forceu** [comment]
Did you modify the `SCRIPT_LOCATION` variable in the script?

**Comment by ChadOhman** [comment]
`SCRIPT_LOCATION` and `SERVER_ADDRESS` are correct.

**Comment by Forceu** [comment]
In that case uncomment line 9, 12 and 101 (import requests, SERVER_ADDRESS=... and requests.get(SERVER_ADDRESS+'?add='+data)) and comment line 99 (os.system("sudo ...) - does that work for you?

**Comment by ChadOhman** [comment]
Well, I did that, and I like that approach better (now that I've read the python)... I'm now wondering if the problem here is the input itself. The scanner works as if it's a keyboard, putting a CF LF at the end of the translated barcode. I can program it to only append a CF or LF, or not at all, but this doesn't seem to change my result (currently nil).

I added a `print data` to the else in `grabInput.py` and here's the result of scanning 'BBUDDY-I'

![2019-11-10 14_42_25-10 0 20 2 (raspberrypi) - VNC Viewer](https://user-images.githubusercontent.com/2351/68551269-61f4d800-03c8-11ea-9224-a28ac058b76a.png)

**Comment by ChadOhman** [comment]
Update: Somehow, a reboot of the raspberry pi solved it. It's printing perfectly into the terminal now and `grabInput.py` is working and I see that reflected on the Screen page.

Thank you for your help!

**Comment by Forceu** [comment]
Great to hear it is working now! :)

**Comment by ChadOhman** [comment]
Unfortunately, it worked once. I went to try using the system in the kitchen, plugged the pi back in and I'm seeing now that something happens to the scanner's input when I run grabInput.py. It'll return `BBUDDY-I` until I run the script, at that point it returns `4=5`.

I'm not sure what's going on here but I know 4 does not equal 5.

**Comment by ChadOhman** [comment]
Adding onto this - I'm able to get the regular output back if I run `grabInput.py` a second time. It doesn't seem to be recognizing `"KEY_ENTER"` though the scanner is returning a CFLF at the end of each scan.

**Comment by ChadOhman** [comment]
Closing this again - I ended up writing my own script to listen to /dev/input/event1 instead of taking over the scanner's raw input, mapping it's output to the US keyboard and sending the request to barcodebuddy.
Thanks again for all of your help with this.

**Comment by Forceu** [comment]
Ah great! Would you mind sharing your script? Maybe this would be a better approach for the example script :)

**Comment by ChadOhman** [comment]
Pull request created! #18
