### ISSUE TITLE
Grocycode stockentry barcode not processed

### ISSUE THREAD

**Issue by llewy** [Forceu/barcodebuddy#170]
So I've attached a labelwriter to my Grocy instance to print datamatrix-codes with stockentry (due date). In the changelog and code I see that this should be processed in Barcode Buddy but it isn't. It's being recognized as Unknown Barcode, while Grocy itself handles it fine:

![image](https://user-images.githubusercontent.com/525767/147820326-df35dce4-78d9-4239-a355-43aa65673518.png)

Not sure where to search for, running 1.8.1.4 in Docker

**Comment by Forceu** [comment]
Thank you for raising the issue. Are you using a physical barcode scanner? I just saw that the default script included in Barcode Buddy does not transmit colons, which is probably the reason why it is not recognised. Does it work if you paste the content of the barcode into the entry field on the Barcode Buddy main page (by clicking on the "add barcode" button)?

**Comment by llewy** [comment]
Yes, that works :-)

**Comment by Forceu** [comment]
Alright, thanks! In case please update your grabber file to one of the changed files in 666dfb7. :)

**Comment by llewy** [comment]
Thanks, that was a quick one. Any change you push a new release as well? I'm using the Docker-version of BB and I see it relies on versions. :-)

**Comment by Forceu** [comment]
The change should be automatically applied the `latest-dev` image, if not let me know!

**Comment by llewy** [comment]
Fixed and verified!

**Comment by jeremy-parks01** [comment]
Marc,
Thank you for your work on this amazing project.   I am new to Grocy and working on using BBuddy to automate my Grocy inventory operations.  I've got a physical barcode scanner attached to an Android tablet and I am having the exact same issue as described above.  On the tablet I can confirm the GrocyCode scans correctly as `grcy:p:380`.  When I can via the app I get the error that a product can't be found for` GRCYP380` and then allows me to add the barcode from the Unknown Barcodes menu.  I have Barcode Buddy deployed with Docker Compose using the `latest-dev` image.   I have looked in the docker container and changes described in the following [Commit](https://github.com/Forceu/barcodebuddy/commit/666dfb77852f9a6b58014559a0deab9af2fb6500) are indeed present.  Anything I can do to troubleshoot?

**Comment by jeremy-parks01** [comment]
@Forceu  
Thank you for the quick response.  To further test I sent some test payloads to the BarcodeBuddy API through Postman and those requests with the colon are being handled properly.   I think this is specifically related to the Android app and is note in this [Bug](https://github.com/Forceu/barcodebuddy-android/issues/20). I am not much of a Java developer but I will have a look as well.
