### ISSUE TITLE
Bug: Action required for Tare-Items in Inventory Mode

### ISSUE THREAD

**Issue by LordofAgents** [Forceu/barcodebuddy#171]
Greetings,
first thank you for this awesome software!
BarcodeBuddy asks to input the weight of tare-items, even when the mode "Inventory" is set. I use the docker image Version 1.8.1.4 and the Android-App.

Steps to reproduce:
- Set to Inventory-Mode with the code BBUDDY-I
- Scan an item with tare-handling enabled

Expected behaviour: 
- BarcodeBuddy shows on the screen.php the amount of the item (e.g. 1 kg of potatos)

Actual behaviour:
- BarcodeBuddy put the item in the "action required" list and output "Action required: Enter weight for X" 
- Asks for weight

Is this caused by any settings, or is this a bug?
If you need additional information, just ask.

Thank you for reading this bad english-text xD

**Comment by Forceu** [comment]
Ah thanks a lot, that is indeed a bug! I will probably fix it today and report back

**Comment by LordofAgents** [comment]
Great, thank you!
Second Bug, or even more a Feature Request: When I am in Inventory Mode, and I scan an unknown barcode, which I scanned before but didnt import in Grocy, it does not show the quantitiy but increases it. 

Steps to Reproduce for second Bug/FR:
- Scan unknown code in Purchase Mode
- Change to Inventory Mode
- Scan same unknown barcode
Barcodebuddy increases the quantity and does not show it.

Should I open a new issue for that?
Thanks for your awesome work!
