### ISSUE TITLE
Bug: Inventory does not show the quantity

### ISSUE THREAD

**Issue by LordofAgents** [Forceu/barcodebuddy#172]
Hello again,
this has maybe something to do with #171 : I updated BarcodyBuddy to latest-dev / 1.8.1.4 and now, it does not show the quantity of the (to grocy known) product on screen.php. It only appears on the app as toast message and in the buddybarcode log (Processed Barcodes).
Is this a bug, or is that intended?

Thank you again!

**Comment by Forceu** [comment]
Thanks, I missed that issue, I will look into it!

**Comment by Forceu** [comment]
Fixed in 7f32286
