### ISSUE TITLE
ProviderJumbo.php is broken - and I can't find the fix

### ISSUE THREAD

**Issue by PiAir** [Forceu/barcodebuddy#183]
Okay, maybe someone here can get this problem fixed, cause I'm hitting a dead end.
After fixing [ProviderAlbertHeijn.php](https://github.com/Forceu/barcodebuddy/blob/master/incl/lookupProviders/ProviderAlbertHeijn.php)  I tried to do the same with [ProviderJumbo.php](https://github.com/Forceu/barcodebuddy/blob/master/incl/lookupProviders/ProviderJumbo.php). Because that one doesn't work (either). I noticed it when scanning Jumbo housebrand items. Like [this 3-in-1 foil](https://www.jumbo.com/producten/jumbo-3-in-1-folie-15-meter-177459ROL) with barcode 8718452117406. Figuring out what the actual error (a 403 message) was, took some time because I'm using Barcode Buddy Version 1.8.1.4 inside of Home Assistant (meaning it runs in a Docker container on a Raspberry Pi) and the code is set up in a way that these kind of errors are not logged.

Additionally, confusing during debugging was that in itself the API call made [https://mobileapi.jumbo.com/v12/search?q=8718452117406](https://mobileapi.jumbo.com/v12/search?q=8718452117406) works without a problem if you run it in a browser on your desktop.
But even if I isolate the logic of the request from the rest of the application and use a separate php file on a stand-alone server away from Home Assistant:
```
<?php
$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://mobileapi.jumbo.com/v12/search?q=8718452117406',
  CURLOPT_FRESH_CONNECT => true,
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 5,
  CURLOPT_CONNECTTIMEOUT => 5,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTPGET => true,
  CURLOPT_HTTPHEADER => array(
    'Host: mobileapi.jumbo.com',
    'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0',
    'Accept: application/json' 
  ),
));

$response = curl_exec($curl);
curl_close($curl);
echo $response;
?>
```
(I added the user-agent and host in an attempt to get it to work) 
The result still is a 403 error **Access Denied
You don't have permission to access "http://mobileapi.jumbo.com/v12/search?" on this server.**

I was able to get it (te request) to work in Postman on my desktop (that is where the initial standalone PHP code comes from), it works using the Python code from [jumbo.py](https://github.com/bartmachielsen/SupermarktConnector/blob/master/supermarktconnector/jumbo.py) by Bart Machielsen. I even can get it to work using PHP if I switch to HTTP_Request2:

```
<?php
require_once 'Net/URL2.php';
require_once 'HTTP/Request2/Adapter.php';
require_once 'HTTP/Request2/SocketWrapper.php';
require_once 'HTTP/Request2/Response.php';
require_once 'HTTP/Request2.php';
require_once 'HTTP/Request2/Observer/Log.php';

$request = new HTTP_Request2();
$observer = new HTTP_Request2_Observer_Log();
$request->attach($observer);
$request->setUrl('https://mobileapi.jumbo.com/v12/search?q=8718452117406');
$request->setMethod(HTTP_Request2::METHOD_GET);
$request->setConfig(array(
    'follow_redirects' => TRUE
));
$request->setHeader(array(
    'Host' => 'mobileapi.jumbo.com',
    'User-Agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0'
));
$request->setBody('');
try {
  $response = $request->send();
  if ($response->getStatus() == 200) {
    echo $response->getBody();
  }
  else {
    echo 'Unexpected HTTP status: ' . $response->getStatus() . ' ' .
    $response->getReasonPhrase();
  }
}
catch(HTTP_Request2_Exception $e) {
  echo 'Error: ' . $e->getMessage();
}

?>
```
This returns the expected result (being the same json as you would get if you open https://mobileapi.jumbo.com/v12/search?q=8718452117406 in your browser).

I know I read somewhere that Jumbo is actively blocking bots from using the API. Which is within their right since they never provided the api for this kind of use. I just can't figure out what in the CURL call is so specific that it recognizes that one as a bot while being perfectly okay with the other two.

So, I'm stuck, any ideas?

**Comment by Forceu** [comment]
It looks that the API has changed, fixed in d564ee0.
