### ISSUE TITLE
Installation of missing curl and redis

### ISSUE THREAD

**Issue by juhagenah** [Forceu/barcodebuddy#190]
Hi,
I installed Barcode Buddy BB) on a Raspberry Pi following the bare metal approach for apache2.
On setup BB states 
Not installed: curl (required)
Installed: date
Installed: sqlite3
Installed: json
Installed: sockets
Not installed: redis (required)

I tried:
  sudo apt-get install php php-fpm php-curl php-date php-json php-sqlite3 php-redis redis redis-server sudo screen evtest
and 
  sudo apt-get install php7.4 php7.4-fpm php7.4-curl php7.4-date php7.4-json php7.4-sqlite3 php7.4-redis
The answer was: 
  php-redis will be used instead of php7.4-redis, php7.4--date could not be found, 

How can I solve the issue?
Jens-Uwe

My setup is:
  BB Version is 1.8.1.4.
  OS is Raspian latest (based on Debian 11 Bullseye
  PHP is 7.4:
   apt list php says: php/stable,now 2:7.4+76 all  [installiert])
   apt list php7.4 says: php7.4/stable,now 7.4.28-1+deb11u1 all  [installiert]
   apt list php7.4* says:
php7.4-bcmath/stable 7.4.28-1+deb11u1 armhf
php7.4-bz2/stable 7.4.28-1+deb11u1 armhf
php7.4-cgi/stable 7.4.28-1+deb11u1 armhf
php7.4-cli/stable,now 7.4.28-1+deb11u1 armhf  [Installiert,automatisch]
php7.4-common/stable,now 7.4.28-1+deb11u1 armhf  [Installiert,automatisch]
php7.4-curl/stable,now 7.4.28-1+deb11u1 armhf  [installiert]
php7.4-dba/stable 7.4.28-1+deb11u1 armhf
php7.4-dev/stable 7.4.28-1+deb11u1 armhf
php7.4-enchant/stable 7.4.28-1+deb11u1 armhf
php7.4-fpm/stable,now 7.4.28-1+deb11u1 armhf  [Installiert,automatisch]
php7.4-gd/stable,now 7.4.28-1+deb11u1 armhf  [installiert]
php7.4-gmp/stable 7.4.28-1+deb11u1 armhf
php7.4-imap/stable 7.4.28-1+deb11u1 armhf
php7.4-interbase/stable 7.4.28-1+deb11u1 armhf
php7.4-intl/stable,now 7.4.28-1+deb11u1 armhf  [installiert]
php7.4-json/stable,now 7.4.28-1+deb11u1 armhf  [Installiert,automatisch]
php7.4-ldap/stable 7.4.28-1+deb11u1 armhf
php7.4-mbstring/stable,now 7.4.28-1+deb11u1 armhf  [installiert]
php7.4-mysql/stable 7.4.28-1+deb11u1 armhf
php7.4-odbc/stable 7.4.28-1+deb11u1 armhf
php7.4-opcache/stable,now 7.4.28-1+deb11u1 armhf  [Installiert,automatisch]
php7.4-pgsql/stable 7.4.28-1+deb11u1 armhf
php7.4-phpdbg/stable 7.4.28-1+deb11u1 armhf
php7.4-pspell/stable 7.4.28-1+deb11u1 armhf
php7.4-readline/stable,now 7.4.28-1+deb11u1 armhf  [Installiert,automatisch]
php7.4-snmp/stable 7.4.28-1+deb11u1 armhf
php7.4-soap/stable 7.4.28-1+deb11u1 armhf
php7.4-sqlite3/stable,now 7.4.28-1+deb11u1 armhf  [installiert]
php7.4-sybase/stable 7.4.28-1+deb11u1 armhf
php7.4-tidy/stable 7.4.28-1+deb11u1 armhf
php7.4-xml/stable 7.4.28-1+deb11u1 armhf
php7.4-xmlrpc/stable 7.4.28-1+deb11u1 armhf
php7.4-xsl/stable 7.4.28-1+deb11u1 all
php7.4-zip/stable 7.4.28-1+deb11u1 armhf
php7.4/stable,now 7.4.28-1+deb11u1 all  [installiert]

**Comment by Forceu** [comment]
Thanks for the issue. If you try the second command without `php7.4-date` it should work, if packages are not found, apt aborts the whole operation.

Try `sudo apt-get install php7.4-curl php-redis` and then restart the Raspberry Pi. Let me know if that works for you

**Comment by juhagenah** [comment]
My fault was not to restart apache2 service after adding the missing dependencies. Now, it works. Sorry for the inconvinience

**Comment by Forceu** [comment]
Great to hear it is working now!
