### ISSUE TITLE
Feature Request: Product Name Language

### ISSUE THREAD

**Issue by hermann-san** [Forceu/barcodebuddy#196]
I'm based in Germany and when I scan new products, it would be nice if I would get a product name/description in German language.
When I actually scan the products, I often get other languages. 

It looks like at least one provider (OpenFoodFacts) provides a language tag,

**Comment by Forceu** [comment]
Thank you for your feedback! By default OpenFoodfacts uses English, if available. It would be possible to set a different default language, I will add it to my todo list.

**Comment by NuclearCookie** [comment]
I would love this as well. Being based in Belgium, products can have a Dutch, French or German translation.
I would be willing to contribute to this tool, do you have any pointers on where to start with this feature?

**Comment by Forceu** [comment]
Added in a93de5e172430e8bcd586ca0c1835fb453376c34, You can now add the entry `DEFAULT_LOOKUP_LANGUAGE` to `config.php` (see example here: https://github.com/Forceu/barcodebuddy/blob/a93de5e172430e8bcd586ca0c1835fb453376c34/config-dist.php#L82) and specify your language (e.g. "de" for German or "fr" for French).

**Comment by hermann-san** [comment]
Thanks a lot!
I'm on Yunohost with Grocy, so I have to wait for the next release and then change the file, that is on Yunohost at /var/www/grocy  (execute su before cd there - Yuno specific)
