### ISSUE TITLE
"Screen" screen is not working for Grocy desktop (Websocket server is not running)

### ISSUE THREAD

**Issue by bluckholl** [Forceu/barcodebuddy#205]
Hi,
I have installed Grocy desktop 2.3.1,
All is working except "Screen" screen that show "rror 10061: No connection could be made because the target machine actively refused it".
In the settings it says "Websocket server is not running! No connection could be made because the target machine actively refused it"

How can I fix it?

Thanks!

![image](https://user-images.githubusercontent.com/2509820/210135830-ac81adaf-9c4b-4a46-b6e7-e0cb3332f90b.png)

**Comment by Forceu** [comment]
Hi, unfortunately this is unrelated to the project, please open an issue in https://github.com/grocy/grocy-desktop

Thanks!
