### ISSUE TITLE
Bug: Carriage return is added on Windows

### ISSUE THREAD

**Issue by Forceu** [Forceu/barcodebuddy#217]
Issue appears for manual multi-line entries

**Comment by mcrummett** [comment]
Hey.  I mentioned this via Reddit.  Looking into it more, it seems my scanner is doing the carriage return after each scan.  However i guess Barcode Buddy shouldnt be reading this as &#13; so still a bug of sorts?

**Comment by mcrummett** [comment]
addition:  okay so manually entering a barcode then hitting enter for a new line and then entering another barcode ends up with the same issue of &#13; being added at the end.  So definitely a BB issue i think

**Comment by Forceu** [comment]
Fixed in 9871ab88e1201b3b43c549133269422ef499e851
