### ISSUE TITLE
Ability to use a phone's camera

### ISSUE THREAD

**Issue by lucasff** [Forceu/barcodebuddy#22]
Would be great if I could use my phone to scan barcodes, so the API querying adds products I have in my pantry. This is really useful for your first time using Grocy, since you would need to manually type each product's name.

**Comment by Forceu** [comment]
Thanks, I will add that to the to-do list!

**Comment by llewy** [comment]
Besides I want to mention that the Docker image is working like a charm, a little hack I use to use my Android's camera as a barcode scanner.

In index.html change the 'add' prefix for the GET-command in 'text'  (twice).

Download the app ' QR & Barcode Scanner POST & GET request to server'.
Go to settings and add a GET request with ' http://***.***.***.***/index.php

**Comment by Forceu** [comment]
Good idea, thank you! I created a commit that parses the `text` parameter as well 

68ee60c8645a4449689ed8bd8cc9cf3c4e2defa1

**Comment by llewy** [comment]
Nice! Can you update the docker image as well? 

Thanks

**Comment by Forceu** [comment]
Sure, you can download it with `docker pull f0rc3/barcodebuddy-docker:lastest-dev`

**Comment by JmzTaylor** [comment]
So I made a thing.  Didn't like the options on the Play Store.  Open source that just works with Barcode Buddy  https://github.com/JmzSoftware/BuddyScanner

**Comment by Forceu** [comment]
Oh wow, that's amazing, thank you!
I might work on it a bit as well - I have about 10 years of experience with Android programming. Do you have a PlayStore Developer account? If not I could upload it myself.

**Comment by JmzTaylor** [comment]
I thought about it but didn't feel like putting the effort towards the play
store graphics and such.  Feel free to upload if you want.  I signed the
APK with my keys so prolly best to compile for yourself to sign with yours

**Comment by Forceu** [comment]
Sure, no problem :) Maybe I find some time to work on it tomorrow, to make it a little bit better looking - but I have to admit, I am not really good at UI design 😅

**Comment by JmzTaylor** [comment]
Me either. But it's pretty straightforward.  One fab to tap to scan and it
automatically sends to server and adds to a recyclerview.

**Comment by garrettdowd** [comment]
Are there any solutions for iPhone users? The built-in QuaggaJS for Grocy does not work well (I think I have gotten it to scan a barcode successfully only once).

**Comment by Benje712** [comment]
You could easily use the native apple shortcuts app. The supplied barcode scanner in it is quite good.

**Comment by Benje712** [comment]
![E5C5D98B-88B7-41DF-9444-9ED66C0F0D9E](https://user-images.githubusercontent.com/40608221/78026297-abd06180-735b-11ea-81fc-72298f709614.jpeg)

**Comment by garrettdowd** [comment]
This works surprisingly well!! It didn't even occur to me to try this. Thanks! 

For other people's reference, I found the last action under Web->Web Requests->Get Contents of URL

Maybe add this to the [documentation](https://barcodebuddy-documentation.readthedocs.io/en/latest/usage.html)?

**Comment by Benje712** [comment]
Glad you figured it out and thanks for sharing! I have mine configured in a similar way.
I really like the option of adding a Shortcut to the Widget Screen for quick access. You can even combine it with the API from Grocy to automaticly display the name of the Product when you consume something....

**Comment by Forceu** [comment]
I finished writing an official app, you can find the preview version attached.

It will probably take a couple of days until it is visible in the PlayStore. Make sure to update to the current master if you are using the app before the 1.5 release.
[app-release.zip](https://github.com/Forceu/barcodebuddy/files/4452573/app-release.zip)

**Comment by enchained** [comment]
> EDIT: Modularized the shortcut a bit so that you can select whether you are purchasing/consuming/opening/etc before scanning. https://www.icloud.com/shortcuts/0f3c43f599a84df299d3e55c145bfe18 (must visit on iOS)

@garrettdowd Thanks, your iOS shortcut is really nice, it worked after I edited the URL. Could you please update it to use `https://your.bbuddy.url/api/action/scan?apikey=myApiKey&add=`, and rename the shortcut to mention Barcode Buddy, so it won't get mixed up with direct Grocy shortcuts? And maybe add an alert with data.result text at the end:
```
Get Value for data in Contents of URL
Get Value for result in Dictionary Value
Show alert Dictionary Value, Show More: Title Result, Show Cancel Button disabled
```
I could try sharing it myself, but not sure how to properly share shortcuts without my apikey, and wouldn't want to take the ownership anyway.

 
@Forceu I think it could be useful to a lot of people if this shortcut was featured in the manual, cause after reading the documentation I was confused whether I could use Barcode Buddy with iOS devices at all, but this shortcut worked pretty well once I edited the URL.

**Comment by cl93a** [comment]
Is there an option to switch the camera (e.g. the front camera of a device, with the mobile app)?

**Comment by cl93a** [comment]
Is there an option to change the camera in the app (e.g. front camera)? Would love to use this with a tablet that is on a stand.
