### ISSUE TITLE
Jumbo API

### ISSUE THREAD

**Issue by groetg** [Forceu/barcodebuddy#220]
The api to Jumbo website has been updated, it should now be version V17
So 'https://mobileapi.jumbo.com/v14/search?q=' should be 'https://mobileapi.jumbo.com/v17/search?q='
I installed barcode buddy via CA in Unraid and don't know how to adjust this manually.

**Comment by Forceu** [comment]
Thanks, I will fix this in the next release

**Comment by Forceu** [comment]
Fixed in 55bbc03d873d637b0aa8282468c0fc3f9da39776
