### ISSUE TITLE
Albert heijn API error

### ISSUE THREAD

**Issue by k-brok** [Forceu/barcodebuddy#224]
Hi,

I installed both grocy and barcode buddy with the docker-compode in portainer:

version: '2.4'

services:

  frontend:
    image: "grocy/frontend:v4.0.3"
    privileged: true
    build:
      args:
        GROCY_VERSION: v4.0.3
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-frontend
    depends_on:
      - backend
    ports:
      - '8080:8080'
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped

  backend:
    image: "grocy/backend:v4.0.3"
    privileged: true
    build:
      args:
        GROCY_VERSION: v4.0.3
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-backend
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
      - /var/www/data/viewcache:mode=755,uid=82,gid=82,size=16m
    volumes:
      - app-db:/var/www/data
    restart: unless-stopped

  BBuddy:
    image: "f0rc3/barcodebuddy:latest"
    privileged: true
    environment:
      IS_DEBUG: true
    volumes:
      - bbconfig:/config
    ports:
      - '8081:80'
      - '8082:443'
      
volumes:
  app-db:
  bbconfig:

I run a reverse proxy for ssl handling and redirections (traefik)
With of withou the redirection I get the same issue.

Whenever I scan a barcode I get the following error:
2023-10-04 07:10:18: Unknown barcode could not be looked up. [8718901741817]
2023-10-04 07:10:17: Albert Heijn reported internal error. Please check your URL and API key in the settings menu!

I have debug enabled, but dont know where the log file can be found (nothing in the container log itself)

I hope you know how to solve this issue?

**Comment by Forceu** [comment]
Fixed in 3cc5340
