### ISSUE TITLE
When I click on Create Product, the barcode is not added on Grocy

### ISSUE THREAD

**Issue by StefanoGiu** [Forceu/barcodebuddy#227]
I scan the barcodes successfully with BarCode Buddy app on Android.

The list of new barcodes with proper names is populated on the Barcode Buddy section, but if I click on Create Product, it opens the Grocy page to add the product, populates the name properly, but not the barcode, even if the barcode number is properly set on the BarCode Buddy page.

**Comment by Forceu** [comment]
Hi, that is correct, as there the API to add a barcode to a new product has been removed by Grocy. Once the product is created, Barcodebuddy will however refresh the page and automatically select the new product from the dropdown menu, so once you click on Add or Consume, the barcode will be associated.

**Comment by DoinStuff35** [comment]
My question about this API-Limitation was marked off-topic and as "false claim".

I was pointed at:

https://demo-prerelease.grocy.info/api#/Generic%20entity%20interactions/post_objects__entity_

and this example:

`POST /objects/product_barcodes

{
  "product_id": 13,
  "barcode": "xx123"
}`

So...what am I missing here?

**Comment by Forceu** [comment]
Sorry API was the incorrect term. It used to be possible to pass the barcode as a GET parameter to the form URL that is used to create the new product. Now it is only possible through the API
