### ISSUE TITLE
Scanning with USB Barcode Scanner does not work

### ISSUE THREAD

**Issue by pimboli** [Forceu/barcodebuddy#228]
Hi, 

I connected a USB scanner but it does not show anything on screen when scanning a code.
I opened browser console and I can see that there the Barcode is shown.
What can be the problem?

![CleanShot 2023-12-02 at 12 03 20@2x](https://github.com/Forceu/barcodebuddy/assets/5020679/31adec4b-3fa0-43c8-8b53-5d4a9f79e53f)

For clarification, barcode buddy runs on my nas, and my scanner is connected on my PC and acts as keyboard.

**Comment by Forceu** [comment]
Related to #191, I will probably add that feature soon, thank you
