### ISSUE TITLE
Add to wiki how it looks up product information

### ISSUE THREAD

**Issue by aindilis** [Forceu/barcodebuddy#23]
I was wondering how this looked up product information.  I know there is upcindex.com and nutritionix.com.  I was wondering whether there was some kind of client server setup to aggregate everyone's entries, or whether it pulled from one of these or similar commercial services?

**Comment by Forceu** [comment]
Good idea, thank you! It is using openfoodfacts.org, however I was also considering adding the ability to upload all local barcodes to a server (if the user agrees and creates an account), where other users can look them up.
