### ISSUE TITLE
Unusual scanner I have? Needed to improve grabInput.sh

### ISSUE THREAD

**Issue by sdalbert** [Forceu/barcodebuddy#231]
I don't know why my barcode scanner is unusual, other than it's probably cheap and old, but the provided grabInput.sh file would not work for mine. I spent time figuring out why and it seems that the two facts below are true from what I understand so far.

1. Normal barcode scanners output the barcode characters and then KEY_ENTER.
2. My scanner types "B", then the barcode characters, then "C".

The file portion below is what works for mine. You might tune and merge this into your file? I recognize that this is flawed if the actual barcode's first character is also "B", so it might also need to test if the first two characters are both "B". I'm just trying to be helpful and not very proficient with Bash scripting.

```
enteredText=""
inc=0
is_bc_scanner=false
echo "[ScannerConnection] Waiting for scanner input"
evtest --grab "$deviceToUse" | while read line; do
  key="$(returnAllowedCharacter "{$line}")"
  if [[ "$key" != "$NON_ALLOWED_CHAR" ]]; then
    ((inc++))
    if [[ "$inc" == "1" ]] && [[ "$key" == "B" ]]; then
	is_bc_scanner=true
    else
	if [[ "$is_bc_scanner" == true ]] && [[ "$key" != "C" ]]; then
	  enteredText+="$key"
	else
	  inc=0
	  echo "[ScannerConnection] Received: $enteredText"
	  if [[ "$enteredText" == "$SPECIAL_BARCODE" ]]; then
	    specialAction
	  else
	    if [[ $USE_CURL == false ]]; then
		sudo -H -u $WWW_USER /usr/bin/screen -dm /usr/bin/php "$SCRIPT_LOCATION" $enteredText
	    else
		curl "${SERVER_ADDRESS}action/scan?apikey=${API_KEY}&add=${enteredText}"
	    fi
	  fi
	  enteredText=""
	fi
    fi
  fi
done
```

**Comment by Forceu** [comment]
Thank you for the input. Normally there are special barcodes you can scan to change the behaviour. Do you still have the manual?

**Comment by sdalbert** [comment]
You definitely jogged my memory with that. I am sure you are correct and I have a distinct memory of messing around with its configuration using barcodes many, many years ago.
