### ISSUE TITLE
PZN Support

### ISSUE THREAD

**Issue by JohannesFleischer** [Forceu/barcodebuddy#236]
I am totally new to barcodebuddy and just starting to use it on my sick days.

And the first things I tried out were the meds I had at hand.
But then I realized, that none of them got recognized.

So they are obviously not in any of the databases.

After a quick search I found out that a Database holding all PZN codes exists and is managed by the [IFA](https://www.ifaffm.de/en/home.html) with the IFA being an Information service provider 
So wanted to ask if there were already some thoughts about adding the PZN numbers or if that would be possible in general.

Maybe it would be possible to contact them to add parts of their data to the federation.

**Comment by Forceu** [comment]
Hi, that does sound like a good idea, however I could not find any public database access for the PZN. I assume, that it is a paid service. I will contact them, but I doubt, that they offer the service for free. I keep this post updated, once I receive a reply.

**Comment by Forceu** [comment]
I have not received any reply at all. I will close this issue - if anyone does have access to these kind of datasets, please let me know and I will include it in the Federation server!
