### ISSUE TITLE
Invalid api keys

### ISSUE THREAD

**Issue by pmkruyen** [Forceu/barcodebuddy#237]
👋 thanks for this great tool.

I installed Grocy as HA addon and made the API keys for Barcode Scanner. 

Unfortunately, I getting the error invalid API key, like #154. Has this problem being resolved or do I need to use my ip address instead of my url http://homeassistant.local?

Or am I making a mistake?

Let me know if more info is needed or if I should ask this question on Reddit. 

Thanks

edit: obviously I can try this tomorrow too, it’s a little to late 😊

**Comment by pmkruyen** [comment]
Solved! I was using the addon url in HA instead of the url in the browser.

**Comment by carbon66** [comment]
> Solved! I was using the addon url in HA instead of the url in the browser.

@pmkruyen Are you able to clarify what address you ended up using? I have the same issue, but I can't find any address to work. 
Thanks!

**Comment by pmkruyen** [comment]
After installing the Grocy Addon in HA, the ui becomes available through Ingress; I used that url for the API keys first. But that gave an error. Browsing to the url http://192.163.4.888:9192 on which my Grocy add on is served too, solved the issue.

Hope that this solved your issue too.

**Comment by HNCloudPrivate** [comment]
I am experiencing a similar situation.

I have Grocy running in HA. I'm connecting to my network over a Tailscale network.

When I install the BarcodeBuddy addon I do the following.


1.) Set up the port in the Grocy Addon Networking settings as described (9192)

2.) Create an API key in the Grocy Addon for BarcodeBuddy

3.) Set the BarcodeBuddy Configuration as follows:
    * Require_api_key = true
    * disable_auth = false
    * debug = false
    * curl_allow_insecure_ssl_ca = true
    * curl_allow_insecure_ssl_host = true

4.) log into Barcode Buddy

5.) On Barcode Buddy setup page homeassistant.local:9192/setup.php
   Grocy API URL:  http://homeassistant.local:9192/api/
   Grocy API Key: xxxxxxx$###$@

6.) Get error  "Unable to connect to API: Could not connect to server"

7.) Repeat Step 5.) using varying Grocy API URLs
  * https://a0d7b954-grocy:9192/api/  -- Hostname for Grocy
  * https://172.30.232:9192/api/  -- Docker0 IP
  * https://172.30.32.1:9192/api/ -- Hassio docker IP

8.) Get same errors as in Step 6.  

I've tried setting the port forwarded via my router for external 9192 requests.
