### ISSUE TITLE
encoding issue when looking up bacode containing special characters

### ISSUE THREAD

**Issue by coldtobi** [Forceu/barcodebuddy#240]
For example, when scanning "4061458056618" , the name becomes 'Cashew-Kerne - geröstet \&\#38; gesalzen', the ampersand is incorrectly encoded.

Not sure why that is, the html source code looks fine. 

(this is with barcode buddy installed as home assistant addon, if that makes a difference, and with firefox.)

**Comment by Forceu** [comment]
Thanks for the feedback! Fixed in 369798d
