### ISSUE TITLE
Respect qu_factor_purchase_to_stock when adding to stock

### ISSUE THREAD

**Issue by ict** [Forceu/barcodebuddy#37]
Hi and thank you for this cool addon!

When creating a product in grocy, you have the option to specify a purchase quantity unit as well as a stock quantity unit. You can also specify a factor that gets applied when you use Grocy's web UI.
This is useful for example to have a carton of eggs as a barcode and scanning it will add 6 eggs, but when consuming you want to consume one egg at a time.

The api exposes this factor as `qu_factor_purchase_to_stock`. It would be cool if Barcode Buddy could respect this factor when in "Add" mode. Currently, one item of stock is added, regardless of the value of this factor.

**Comment by Forceu** [comment]
Thanks, I will add it to my todo list. Currently you can also use the BBUDDY-Q-X code (replace X with the number of items in the pack after scanning the barcode). That way every time you scan the barcode, it will add X units instead of 1, but only consume 1.

**Comment by goldelehr** [comment]
This is also quite useful for fluids like milk where a package of milk equals 1000 Milliliters (the unit needed for most recipes).

**Comment by Forceu** [comment]
Added in https://github.com/Forceu/barcodebuddy/commit/2cfeda7cfc825764bffc3953f727992bb27b5d91
