### ISSUE TITLE
Feature-request: Add colruyt.be

### ISSUE THREAD

**Issue by XtremeCoder007** [Forceu/barcodebuddy#38]
Hello,

I was wondering if it is possible to add a major store-chain of my country.

I've done some digging with insomnia and got to this :

https://cogomw.colruyt.be/cogomw/rest/nl/8/articles/search.json?barcode=5400141398380&oAuth=<oAuth_token>

and it would return:
`{
  "params": [
    {
      "string": "barcode",
      "string-array": [
        "5400141398380"
      ]
    },
    {
      "string": "service",
      "string-array": [
        "search"
      ]
    },
    {
      "string": "languageCode",
      "string-array": [
        "nl"
      ]
    },
    {
      "string": "oAuth",
      "string-array": [
        "<oAuth-token>"
      ]
    },
    {
      "string": "version",
      "string-array": [
        "8"
      ]
    },
    {
      "string": "type",
      "string-array": [
        "json"
      ]
    }
  ],
  "status": {
    "code": 0,
    "meaning": "SUCCESS"
  },
  "data": {
    "@class": "colruyt.cogomw.bo.ArticleInfo",
    "searchResults": [
      {
        "colruyt.cogomw.bo.RestTreeBranch": {
          "id": "-1",
          "description": "Zoekresultaat"
        },
        "list": [
          {
            "id": "42681",
            "brand": "BONI S.",
            "description": "Al.pollakf. graatl. MSC",
            "content": "5st 800g",
            "overviewImage": "/step/JPG/JPG/200x200/std.lang.all/06/76/asset-1890676.jpg",
            "units": [
              "S"
            ],
            "defaultUnit": "S",
            "price": "5,99",
            "priceUnit": "st",
            "unitPrice": "7,49",
            "unitPriceUnit": "kg",
            "discountPrice": "5,39",
            "discountPriceUnit": "st",
            "discountQuantity": "3",
            "discountSalableWeightCode": "S",
            "discountSalableQuantity": "3",
            "priceFunction": "function(q,w){return Math.round(q*[5.99,5.39][q<3.0?0:1]*100)/100}",
            "saleable": true,
            "defaultQuantity": "1",
            "ficEnabled": false,
            "isLactoseFree": false,
            "isGlutenFree": false,
            "branchId": "165"
          }
        ]
      }
    ]
  }
}`

Could this be added as a plugin ? 

I'm however not that great at coding.

Thanks for reading,

XtremeCoder007

**Comment by Forceu** [comment]
Thanks for your feedback! How exactly does the oAuth work? Where would you register for that?

**Comment by XtremeCoder007** [comment]
Hi, 

Thanks for the feedback.

Let me explain the process:
Shopper downloads app, register & sign-in
They can select a store to pickup the goods
Add items in the basket, but also search product by activating the barcode-scanner.(right-bottom corner)

I've extracted the apk for you:
https://stack007.stackstorage.com/s/2HbE7nkg1yZLZIN

Also created an account for you on the app if needed.

If needed i can upload the session i've simulated in insomnia.

For what i can see 2 things need to happen:
User logs in and receives an oAuth-token
(Seems to be persistent)

Uses token to authenticate with the api in order to search the Database.

If you have any questions, feel free to ask.

Thanks in advance,

XtremeCoder007

**Comment by Forceu** [comment]
Could reuse code from https://github.com/area3001/ColliScanner/blob/master/colruyt.py

**Comment by XtremeCoder007** [comment]
I can assume, but seems out-dated since the api is now [https://cogomw.colruyt.be/cogomw/rest/nl/8/](https://cogomw.colruyt.be/cogomw/rest/nl/8/)

**Comment by Forceu** [comment]
This seems to be an often changing API, which needs decompiling / creating a user account in order to work. Unfortunately it is out of scope for this project. If anyone is able to implement it however, I would be happy to merge it into the master tree.
