### ISSUE TITLE
API returns malformed Json

### ISSUE THREAD

**Issue by Forceu** [Forceu/barcodebuddy#40]
See https://github.com/Forceu/barcodebuddy/commit/b9a1bc80ea46d62eac73bcc1adb8d7d11eae3ce3#commitcomment-38384817

**Comment by bbreton09** [comment]
Same issue after git pull.

**Comment by Forceu** [comment]
Okay, I had a look at the problem and it is most likely that your server configuration is invalid. What is the output if you open `http://your.bbuddy.url/api/action/scan` in your browser (replacing it with your installation)?

Also please have a look at the documentation for the current unstable version: https://barcodebuddy-documentation.readthedocs.io/en/unstable/setup.html#configuring-apache2

**Comment by bbreton09** [comment]
> api/action/scan

{"data":null,"result":{"result":"Unauthorized","http_code":401}}

My apache config is same as the doc but in HTTPS

**Comment by Forceu** [comment]
Hm weird, so the API seems to be working. Can you please _uninstall_ the app and install the following version: https://github.com/Forceu/barcodebuddy-android/releases/tag/v0.1

Also does this error occur always or only sometimes?

**Comment by bbreton09** [comment]
Same message with v0.1 app, but the product is ok in buddy.

2020-04-09 11:26:37: Product found. Consuming 1 Tablette of Chocolat BLOC lait noisettes entières. Barcode: 7622210765352


The application on the other hand does not take into account the fact that my URL is in HTTPS. I have to correct by hand after the QRCODE scan.

**Comment by Forceu** [comment]
Normally the barcode should automatically be set as HTTPS if it was created with an HTTPS connection. Anyways, I added an input field in 6b372855fa9d28a14a67a050f841f0906ac47bbf so it can be edited before scanning.

Also does this error always occur or only sometimes?

**Comment by bbreton09** [comment]
Always

**Comment by Forceu** [comment]
Okay, in that case please install the debug version. Once a barcode is scanned, it will open a new screen with the response, please attach a screenshot or copy the text.
[app-release.zip](https://github.com/Forceu/barcodebuddy/files/4456982/app-release.zip)

**Comment by bbreton09** [comment]
> Okay, in that case please install the debug version. Once a barcode is scanned, it will open a new screen with the response, please attach a screenshot or copy the text.
> [app-release.zip](https://github.com/Forceu/barcodebuddy/files/4456982/app-release.zip)

I think i found the problème i send request to TTS :)
![image](https://user-images.githubusercontent.com/10090794/78912218-9cea5d00-7a87-11ea-96bc-43e5d1ad8bd7.png)

**Comment by Forceu** [comment]
Okay, thanks!

**Comment by bbreton09** [comment]
But the URL is not this one i user in EventReceiver.php and i dont know how the app take this one.
