### ISSUE TITLE
BarcodeBuddy API does not stay in the set mode

### ISSUE THREAD

**Issue by bigjay517** [Forceu/barcodebuddy#45]
I’m using the BarcodeBuddy API with Apple Shortcuts. My understanding is that when I want to mark an item as purchased I first need to set the mode to STATE_PURCHASED then add the barcode. 

![image](https://user-images.githubusercontent.com/6580243/79293641-3f4c7b00-7ea2-11ea-96aa-bf7b491c4066.jpeg)

When trying to mark an item as purchased I first call the set mode API I receive a successful response. 

![image](https://user-images.githubusercontent.com/6580243/79293748-74f16400-7ea2-11ea-99a6-3def016ce812.jpeg)

For testing I read the mode back to check that it is set correctly. When I do this I see that I am again in mode 0 STATE_CONSUME. 

![image](https://user-images.githubusercontent.com/6580243/79293815-9a7e6d80-7ea2-11ea-9979-3b0d6623ad52.jpeg)

Am I using the API incorrectly, or is there an issue here?

**Comment by Forceu** [comment]
Thanks a lot for your feedback! That was indeed a bug and is fixed now. I will publish an update in the next hour.
