### ISSUE TITLE
 Duplicate barcode in a new grocy product database

### ISSUE THREAD

**Issue by bbreton09** [Forceu/barcodebuddy#46]
when I scan a new product that I add from Buddy, the barcode increases twice in grocy database.
if i save in grocy the double disappears.
See capture

![image](https://user-images.githubusercontent.com/10090794/79333286-8f692300-7f1e-11ea-8cd6-5ff59862a34a.png)

I checked, only one code is sent to the API

In this case i use Scanner Get/Poste android APP. I not have problem every scan.
Unsucess to reproduce from webbrowser request or official Android App.

**Comment by bbreton09** [comment]
To reproduce it is necessary:
1°) Scan a new product.
2°) Create it in grocy from Create in buddy
3°) Return to buddy and click on ADD.
Right after that the barcode is doubled in grocy !

**Comment by Forceu** [comment]
Thank you for your report! Fixed in https://github.com/Forceu/barcodebuddy/commit/e48cee848e7392d8f42665dc7df04db77c81986d
