### ISSUE TITLE
Barcode Buddy Android APP issues

### ISSUE THREAD

**Issue by hmronline** [Forceu/barcodebuddy#49]
Hi, first of all, thanks for developing this!

I have tried to use the Android App, but I was unable to make it work.

First issue was that sanning the QR Code shown an error stating: Invalid QR Code, no setup info found.
I was expecting this to auto-configure the app (setting API URL, protocol, port, and key) as it is can be guess from the documentation, however it seems it only provides the API Key.

After that, the "CONNECT" button was shown.
I would expect some help to understand what I was supposed to type there, but I've tried entering the API URL but two more errors occurred:

If an HTTP URL was entered, it failed stating that "cleartext communications not permitted by network security policy".

If an HTTPS URL was entered, it failed stating that "Trust anchor for certification path not found".
I'm using a self-signed certificate and CA is properly installed on Android device.

Hope this helps to improve the app and make it more usable.

Thanks in advance!

**Comment by Forceu** [comment]
Thank you for your feedback. To create a QR code for the app, please go to the API menu and click on the top right corner on the three dots and then select "Add mobile app". That way a setup QR code is generated.

I think since Android 8.0 custom CAs that are not installed as a system CA aren't allowed for app communication anymore. I will add an option to ignore invalid SSL certificates in the next version however: https://github.com/Forceu/barcodebuddy-android/issues/2

**Comment by llewy** [comment]
I'm only using HTTP and I'm getting the same error. Maybe add this solution as well?

https://better-coding.com/solved-android-cannot-send-data-to-the-server-cleartext-communication-to-not-permitted-by-network-security-policy/

Thanks anyway!

**Comment by XtremeCoder007** [comment]
If you have a reverse-proxy you can define an ssl certificate (let's encrypt etc) so android wont know.

**Comment by Forceu** [comment]
Ah I forgot that Google added at some point that HTTP connections are not allowed for apps anymore either... I will add it as well: https://github.com/Forceu/barcodebuddy-android/issues/3

As this is all related to the app and not the core application, I will close this issue for now, any further issues related to the app can be submitted here: https://github.com/Forceu/barcodebuddy-android

**Comment by Forceu** [comment]
I updated the app - it might take some time until it is available in the Play Store. You can also download the update here: https://github.com/Forceu/barcodebuddy-android/releases/tag/v0.2
