### ISSUE TITLE
 Table adapts to resolution

### ISSUE THREAD

**Issue by bbreton09** [Forceu/barcodebuddy#50]
![image](https://user-images.githubusercontent.com/10090794/79489823-31bb0080-801c-11ea-9a22-bc24b9ef8558.png)
Would it be possible to have all of the options in each row fit into the table?
In capture as you can see it is not possible to clic create or delete

**Comment by Forceu** [comment]
Thanks, my product names are rather short, therefore I didn't encounter this problem.
