### ISSUE TITLE
How to grab input on a different host

### ISSUE THREAD

**Issue by jfmcarreira** [Forceu/barcodebuddy#51]
I have barcodebuddy running on my main server. 

This works well when I use my android phone, however would it be possible to run grabInput.sh/py on a different host and send post messages to the main server?

I want to use for example a Rpi to connect to a bluetooth barcode scanner. What do I need to install on the raspberry pi? do I only need the script? I am confused with this variable "SCRIPT_LOCATION: Replace with the location where your index.php file is located"

**Comment by Forceu** [comment]
In that case your best option would be to use the [Python Variant 3](https://github.com/Forceu/barcodebuddy/blob/master/example/grabInput_variant3.py) and replace the URL and API key with yours. 

If the barcode scanner is connected on a different server, you will always need to use the URL. Let me know if that works for you :)

**Comment by jfmcarreira** [comment]
I am trying to use it. Had some problems with the bluetooth connect but it seems I am on a good path now.

How can I get the SCANNER_STR?

**Comment by jfmcarreira** [comment]
Just to let you know that your script worked

However I am not able to keep the scanner paired with the RPI. But that is another problem.

**Comment by Forceu** [comment]
Great to hear it is working now! :)
