### ISSUE TITLE
Feature request: Cache expiration date when unkown barcode is passed

### ISSUE THREAD

**Issue by brygge2** [Forceu/barcodebuddy#53]
First of all, thank you for the amazing work on this project! It's been extremely useful for me.

I'm using the new API added in https://github.com/Forceu/barcodebuddy/commit/0d7eea7f3c8665ab4a924900b2e905bbde3751fb to pass expiration dates along with each barcode to BarcodeBuddy, via a script that collects input from both a barcode reader and a wireless numpad.

This works well for already associated barcodes. However, one issue I noticed is that the expiration date is dropped for unknown barcodes. In that case, my workflow ends up being: (1) scan item, (2) enter expiration date, (3) notice in BarcodeBuddy UI that barcode is unknown, (4) create new product in UI, (5) add item, (6) consume item, then (7) scan item again in order to set the expiration date correctly.

Would it be possible to store the expiration date to the db when calling the insertUnrecognizedBarcode function?

I realize this won't be perfect in the case where $amount > 1. But a reasonable solution may be to for example keep the first or last expiration date and assign to all the added items when the unrecognized barcode is resolved.

**Comment by Forceu** [comment]
Thanks for your feedback, yes that would be a good idea! I will add it to the next commit.

**Comment by Forceu** [comment]
Added in https://github.com/Forceu/barcodebuddy/commit/e48e44c62d7107e461e65549932a624f5a7a034e

**Comment by duracell** [comment]
Sorry for posting here, but @brygge2 I would be really interested in your solution to scan and add expiration date.
Would be great if you could contact me or put a documentation on github :)
