### ISSUE TITLE
Ampersand character (&) breaks import into gorcy

### ISSUE THREAD

**Issue by Lockszmith** [Forceu/barcodebuddy#54]
Scanning barcode: 02185705
It was identified correctly as: Garlic & herb cream cheese spread

It seems that _grocy_ isn't handling the input correctly (and I'll open a bug there as well) but I think an option to replace special chars with '-' or something would workaround this issue easily.

**Comment by Forceu** [comment]
Thanks a lot! I created a pull request for the grocy project to fix the problem https://github.com/grocy/grocy/pull/793
