### ISSUE TITLE
DB Error: DB_Not_Writable: - Can't get barcodebuddy to work

### ISSUE THREAD

**Issue by vorkuta** [Forceu/barcodebuddy#55]
**Error in browser**

`DB Error: DB_Not_Writable: Database file cannot be created, as folder or database file is not writable. Please check your permissions.
Have a look at this link to find out how to do this: How do I make files and folders writable for the web server?`

**Permissions**

`drwxrwxr-x 10 red   www-data 4096 Apr 15 06:13 barcodebuddy`
```
red@yoga:/var/www/barcodebuddy$ ls -l
total 136
drwxrwxr-x 2 red www-data  4096 Apr 15 06:13 api
-rw-rw-r-- 1 red www-data  2904 Apr 15 06:13 config-dist.php
drwxrwxr-x 2 red www-data  4096 Apr 26 17:39 data
drwxrwxr-x 2 red www-data  4096 Apr 15 06:13 docker
-rw-rw-r-- 1 red www-data  1043 Apr 15 06:13 error.php
drwxrwxr-x 4 red www-data  4096 Apr 15 06:13 example
drwxrwxr-x 8 red www-data  4096 Apr 15 06:13 incl
-rwxr-xr-x 1 red www-data 16573 Apr 15 06:13 index.php
-rwxr-xr-x 1 red www-data 35129 Apr 15 06:13 LICENSE.md
-rw-rw-r-- 1 red www-data  4934 Apr 15 06:13 login.php
-rw-rw-r-- 1 red www-data   129 Apr 15 06:13 logout.php
drwxrwxr-x 2 red www-data  4096 Apr 15 06:13 menu
drwxrwxr-x 2 red www-data  4096 Apr 15 06:13 plugins
-rwxr-xr-x 1 red www-data  2731 Apr 15 06:13 README.md
-rw-rw-r-- 1 red www-data    26 Apr 15 06:13 robots.txt
-rwxr-xr-x 1 red www-data  9789 Apr 15 06:13 screen.php
-rwxr-xr-x 1 red www-data  4703 Apr 15 06:13 setup.php
-rwxr-xr-x 1 red www-data  3249 Apr 15 06:13 wsserver.php
```

I'm using Caddy as a webserver. I'm not sure where the permissions issue is, as the output doesn't make this clear, and all of /var/www/barcodebuddy has the group www-user.

**Comment by Forceu** [comment]
Normally it should be enough if the group is www-data, maybe run `sudo chown -R www-data:www-data  /var/www/barcodebuddy ` and try if that is working...

**Comment by vorkuta** [comment]
Thank you. Had not run chown recursively, doh.
