### ISSUE TITLE
Question: Can I scan codes on mobile?

### ISSUE THREAD

**Issue by vorkuta** [Forceu/barcodebuddy#57]
I have barcode buddy running, as well as grocy. In the settings pane I can see

`Successfully connected to Grocy, valid API key.`

and

`Websocket server is running.`

So hopefully my install is all good. 

I'd like to be able to scan the barcodes using my phone, is this possible?

**Comment by Forceu** [comment]
If you have an Android phone, you can download the app: https://play.google.com/store/apps/details?id=de.bulling.barcodebuddyscanner&hl=en

Let me know if it is working for you.

**Comment by vorkuta** [comment]
On, iOS, so no worries. I have used a scanner that allows for consecutive scans and can be copied into text with newlines (Bar-Code).

On an unrelated note, I can't add the barcodes because the 'add' button is off the bottom of the page. Should I add a new issue for this? Thanks @Forceu !

**Comment by Forceu** [comment]
I will create an issue for that later, do you have a screenshot?

**Comment by vorkuta** [comment]
![ezgif-3-daf12a41039f](https://user-images.githubusercontent.com/6390017/80360040-a7be3380-8876-11ea-8ad3-8dac993b595c.gif)
