### ISSUE TITLE
Reverse Proxy Question

### ISSUE THREAD

**Issue by kriddles** [Forceu/barcodebuddy#59]
Hi,

I have grocy setup with nginx as a subdirectory and I am just starting to get Barcode Buddy setup. 

Do you have any instructions available for configuring for a nginx reverse proxy alongside setting up barcode buddy in a subdirectory?

**Comment by Forceu** [comment]
Thanks for your interest! I was thinking of adding an example nginx file for reverse proxy, I will probably add it today or in the next days.

**Comment by Forceu** [comment]
You can find the example here: https://github.com/Forceu/barcodebuddy/blob/master/example/nginxReverseProxy.conf
