### ISSUE TITLE
Add option to set external Grocy URL

### ISSUE THREAD

**Issue by kwcodes** [Forceu/barcodebuddy#61]
I am trying to set up barcode buddy/grocy with `HomelabOS` (https://gitlab.com/NickBusey/HomelabOS/) on a raspberry pi.

I can get the docker containers up and running; however, having a bit more difficulty properly setting up barcodebuddy. It seems like barcodebuddy is not able to connect to the API if I provide the url HomelabOS sets up, i.e. `grocy.<mydomain.local>/api`. I can get around this by inspecting the page and removing the URL's required pattern, and inputting the docker container's hostname for URL, i.e. `grocy_app_1/api`.

This gets the overall functionality of the barcodebuddy working, but the hyperlinks are parameterized based on the `GROCY_BASE_URL`, so those do not work, e.g. https://github.com/Forceu/barcodebuddy/blob/0d7eea7f3c8665ab4a924900b2e905bbde3751fb/index.php#L394-L396

What should I be inputting for the base url in this case?

**Comment by Forceu** [comment]
Thanks for the feedback! Are you adding http:// or https:// in front of the URL?

**Comment by kwcodes** [comment]
Yes, tried both, and without.

**Comment by Forceu** [comment]
Can you post the full URL? I tested the regex, and unless your URL contains a line break (which I'm sure it doesn't), the regex should work.

**Comment by kwcodes** [comment]
Ah sorry, maybe I was not being explicit earlier. If i use the `http://grocy.<mydomain.local>/api` URL, I get the following error:

```
Unable to connect to Grocy! Could not connect to server
```

But using `grocy_app_1/api` (with the required pattern removed) does not result in that error.

**Comment by Forceu** [comment]
Oh okay, thank you. In that case I don't think this is an issue with the docker image per se, the reason for that is that the docker image cannot resolve grocy.<mydomain.local>. Have you tried `http://grocy_app_1/api` ?

**Comment by kwcodes** [comment]
Both `grocy_app_1/api` and `http://grocy_app_1/api` work, but the hyperlinks in barcodebuddy then do not work. 

i.e. it'll generate something like: `http://barcodebuddy.<mydomain.local>/grocy_app_1/product/new?closeAfterCreation&prefillbarcode=<barcode>` or `http://grocy_app_1/product/new?closeAfterCreation&prefillbarcode=<barcode>`, respectively.

**Comment by Forceu** [comment]
Oh I see, so basically the external URL is different from the internal one? I guess it would be possible to add an option to use a different URL for internal communication...

**Comment by kwcodes** [comment]
Yeah, I think that summarizes the issue well. Thanks!

**Comment by Forceu** [comment]
Added in https://github.com/Forceu/barcodebuddy/commit/fa2e98f86ee36e31207056771cf096f980f03321

You can use the latest dev docker image to try it out, pass the argument `-e BBUDDY_EXTERNAL_GROCY_URL=your.url` when creating the container.

**Comment by kwcodes** [comment]
Thanks, will give it a try!
