### ISSUE TITLE
Make available on F-Droid

### ISSUE THREAD

**Issue by totti4ever** [Forceu/barcodebuddy#64]
As this is open source, I'd love to bypass Google's Playstore ✌️

**Comment by Forceu** [comment]
Created merge request: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6741

**Comment by Forceu** [comment]
The PR hast been merged into F-Droid and the app should be available on F-Droid within the next days :tada:

**Comment by rugk** [comment]
Maybe also [link it in the Readme then](https://github.com/Forceu/barcodebuddy#available-for)?
