### ISSUE TITLE
Bare metal installation instructions wrong

### ISSUE THREAD

**Issue by bsmout** [Forceu/barcodebuddy#65]
The installation guide states you need to execute the following command:
apt-get install php-fpm php-curl php-date php-json php-sqlite sudo screen evtest

php-sqlite need to change to php-sqlite3

also there is the assumption php is already installed. Better include apt-get php as well.

**Comment by Forceu** [comment]
Thanks for the heads up! Changed in https://github.com/Forceu/barcodebuddy-documentation/commit/444e0266bef94cf5655cec9aabd13ebbb616cf12
