### ISSUE TITLE
Error looking up product by barcode

### ISSUE THREAD

**Issue by Phoara** [Forceu/barcodebuddy#7]
When I try to look up a barcode, I get the error "Error looking up product by barcode" in the index.php. Is there anything I have to do to make it work?

**Comment by Forceu** [comment]
Thank you for your report! Is Barcode Buddy able to access the internet from your server?

**Comment by Phoara** [comment]
Thank you for the quick reply. I don't know why it shouldn't. Every other service in my Synology web folder works without any problems.

**Comment by Phoara** [comment]
I did a fresh install of Barcode Buddy and now it works. I have no idea why.

**Comment by Forceu** [comment]
Thanks for the report anyways! If the problem occurs again, please let me know!
