### ISSUE TITLE
Return resulting stock after scan

### ISSUE THREAD

**Issue by freakshock88** [Forceu/barcodebuddy#75]
Hi,

For my shopping workflow, it would be very handy to be able to scan a product, (for instance in consuming or purchasing mode) and have the result show (or TTS) the resulting current stock. 

So for instance, if I have 5 bananas in stock, and I use the consuming scan mode, it returns:
"Consuming 1 banana, there are now 4 bananas in stock"

This way, I could scan an item multiple times to correct the current stock, making inventory work way faster. If instead I have to inventory all current stock by inputing a number, this is way more work. 

Is this possible to add?

**Comment by Forceu** [comment]
Thank you for your feedback! I will add it today :)

**Comment by Forceu** [comment]
Added in https://github.com/Forceu/barcodebuddy/commit/183d39dc3e373eb8452ee22302a40ef0c042bc85
