### ISSUE TITLE
Prefill other attributes (eg. calories) when creating a new product

### ISSUE THREAD

**Issue by TheFlyrain** [Forceu/barcodebuddy#76]
Wouldn't it be useful to use more than only the name of the product to create a new product in grocy? Maybe category or nutritions stats?

**Comment by Forceu** [comment]
Thank you for your feedback! While it would  be possible, it would require quite a lot of work to change and also cause some other issues. I will leave it open for the future however.

**Comment by Forceu** [comment]
Unfortunately this feature will not be added, as each provider would need to be changed and grocy code base needs to be adjusted as well
