### ISSUE TITLE
Add barcode to set amount of next consume / purchase

### ISSUE THREAD

**Issue by tboby** [Forceu/barcodebuddy#77]
I'm only just starting to use barcodebuddy/grocy, so do let me know if I'm missing something obvious.

I'd like to use this to track baking supplies, which are almost always bought as packs, and consumed by weight. The setting `USE_GROCY_QU_FACTOR` handles this well for purchasing, and `CONSUME_SAVED_QUANTITY` means I can consume entire packs too. However, I can't see a way to consume an arbitrary quantity, or partial packs.

E.g. the following scenario:
1. Purchase 1 pack of Chocolate (containing 100g)
2. Consume 50g of Chocolate

I had hoped the quantity feature was that, but from looking at https://github.com/Forceu/barcodebuddy/blob/master/incl/processing.inc.php#L437 it seems quantity is meant as a permanent override if you're not using grocy's qu factor, not a temporary modifier for the next command.

**Possible solution:**
Have an alternative quantity mode which is applied to the *next* scan. There are a couple of ways this could be applied, which might make sense in Purchase or other locations too.
1. Apply as an absolute override, with quFactor: If you scan Quantity 2, Consume Chocolate, it consumes `2 * quFactor`
2. Apply as an absolute override, without quFactor: If you scan Quantity 100, Consume Chocolate, it consumes 100 of grocy's stock unit.
This assumes the current quantity mapping isn't needed if you're using quFactor. I'm not sure that's the case.

**Comment by Forceu** [comment]
Thank you for your feedback!
I am afraid, I do not quite understand the question. The following is currently possible:

- Consume 1 unit of the product (default)
- Consume all
- Consume amount of units set with BBUDDY-Q-X
- Consume amount of units set by Grocy with quFactor

What exactly are you suggesting to implement?

**Comment by tboby** [comment]
Sorry, that ended up being a bit rambly.
I'd like to be able to, without changing settings, in one session:

1. Purchase amount of units set by Grocy with quFactor
2. Consume amount of units set by Grocy with quFactor for product A
3. Consume 500 units of product B
4. Consume 100 units of product B

Currently, if I try to do this, the log is:
```
2020-05-25 22:58:28: Product found. Consuming 1 Piece of Test. Barcode: 6A14470D
2020-05-25 22:58:03: Set quantitiy to 2 for barcode 6A14470D (Test)
2020-05-25 22:58:00: Set state to Consume
2020-05-25 22:57:50: Set quantitiy to 2 for barcode 6A14470D (Test)
2020-05-25 22:56:46: Product found. Adding 10 Piece of Test. Barcode: 6A14470D [WARNING]: No default best before date set!
```

I'd suggest that it works as follows:
1. `BBUDDY-P`
2. `6A14470D`
3. `BBUDDY-C`
4. `BBUDDY-QT-500`
5. `6A14470D`

resulting in
1. Set state to Purchase
2. Adding 1000 Grams of Test (quFactor)
3. Set state to Consume
4. Set temporary quantity to 500
5. Consuming 500 Grams of Test

**Comment by Forceu** [comment]
Ah I see, that makes more sense now ;) I will add it to my todo list

**Comment by rdgerken** [comment]
Hi, I just started using Grocy and Barcode Buddy.  I'm having some issues understanding how the quantities are supposed to work, and I think it might be somewhat related to this issue, so I hope you don't mind if I ask here.

Here is the scenario:
1. I add a product into Grocy
2. This product is a 33.5 ounce box of tomato sauce.
3. When configuring the product, I select:
           -Quantity Unit Stock of "Ounce"
           -Default quantity unit purchase "Box"
           -Factor Purchase to Stock Quantity Unit "33.5"
4. This means that each time a "Box" is purchased, 33.5 ounces are added to stock
5. I then edit the barcode for this box, and enter Quantity Unit (Ounces), Amount (33.5)
6. I then add an additional barcode for this product, which happens to be a 12oz can of tomato sauce.
7. I set the Quantity Unit to (Ounces), Amount (12)
8. I go to purchasing, and each time I scan a box, I get 33.5 ounces added to my stock, each time I scan a can I get 12 ounces added to stock.  It works as it should.
9. Now if I do the same through Barcode Buddy - I just get (1 ounce) added each time I scan either the box or the can.  I really don't want to be scanning quantities into Barcode Buddy each time as described above.  Is it possible to just pass the barcode to Grocy and let the specific barcode quantity configuration there sort out the actual amount to add to stock like I have described here?

Thanks!

**Comment by Forceu** [comment]
Thank you for your question! As mentioned in #105, this will be changed with the next release. With the new version each time you scan the barcode and you have set the quantity for that barcode in Grocy, Barcode Buddy will add the quantity with that factor. In that case it would att 33.5 ounces instead of 1 unit.
The new version will be released in the next couple days.

Also I am closing this issue, as it is related to #105
