### ISSUE TITLE
Websockets error (Synology NAS)

### ISSUE THREAD

**Issue by Phoara** [Forceu/barcodebuddy#8]
Sorry for having to bother you with another issue. When I try to run the wsserver.php via Terminal, I get the following error:

> PHP Warning:  Unsupported declare 'strict_types' in /volume1/web/bbuddy/incl/websocket/php-websocket/src/Connection.php on line 3

> Warning: Unsupported declare 'strict_types' in /volume1/web/bbuddy/incl/websocket/php-websocket/src/Connection.php on line 3
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /volume1/web/bbuddy/incl/websocket/php-websocket/src/Connection.php on line 80

> Parse error: syntax error, unexpected ':', expecting ';' or '{' in /volume1/web/bbuddy/incl/websocket/php-websocket/src/Connection.php on line 80

**Comment by Forceu** [comment]
You are using an old version of PHP, I just noticed that the library I was using for the websockets requires PHP7.2

I updated the source code to support PHP5+ now, please update to the latest commit, it should be working now for older PHP versions as well.
