### ISSUE TITLE
Setup android app

### ISSUE THREAD

**Issue by HydrelioxGitHub** [Forceu/barcodebuddy#81]
Hello, 

I've just discover your work through Grocy website and I think this is a great improvement for me. But I'm stuck with the setup.

I've grocy installed in a Hass.io container with a nginx reverse proxy to access it outsite the house. When I start the android app, it asks for a barcode to access Grocy API. But I can't find it in the Grocy API interface (I can only add API keys), and I can't access anything to input url manually. 

Can someone help me with it, I'm missing something.

Thanks for your work and your time.

**Comment by HydrelioxGitHub** [comment]
Ok after reading more carefully the documentation, I've seen it need another setup. It's a bit confusing between "BarcodeBuddy" which is the main part and "BarcodeBuddy app" which is the android app that connect to this part.

**Comment by Forceu** [comment]
Yeah sorry, it is not a standalone app. You can install it on your Grocy server however or if you are using docker, download our docker image.
