### ISSUE TITLE
Add a "baseurl" property

### ISSUE THREAD

**Issue by geransmith** [Forceu/barcodebuddy#85]
I'm attempting to setup an nginx reverse proxy on a subdirectory (<host>/barcode). This works for a lot of things, but I'm unable to login or add mobile apps.

Grocy added a "baseURL" config that allows you to add a subdirectory for cases like this. I'd love if this was added into Barcode Buddy. For now I just set Barcode Buddy to the root location in nginx, since it at least makes it work and I love it so dearly.

**Comment by Forceu** [comment]
Thank you for your feedback! I will add it to my todo list :)

**Comment by Forceu** [comment]
Added in c02638c. Please test it and let me know if it is working :)
