### ISSUE TITLE
Buying a pack does not add the desired quantity

### ISSUE THREAD

**Issue by ZeGuigui** [Forceu/barcodebuddy#87]
I just installed grocy and barcodebuddy. Great job!
However when I buy a "pack" of product, only one item is added when I click the "add" button.

For instance I scanned a "pack of mini babybel x20". I created the product in grocy through the "Create product" button. I set it up as a "pack" with a 1 to 20 conversion factor.

![Capture d’écran 2020-08-17 à 23 34 37](https://user-images.githubusercontent.com/13727111/90446829-5adec100-e0e2-11ea-89df-3775c2124610.png)

Then I add and grocy display a stock of 1 piece.
![Capture d’écran 2020-08-17 à 23 34 59](https://user-images.githubusercontent.com/13727111/90446844-6205cf00-e0e2-11ea-8823-925c9e37ebbd.png)

Is there a way to "buy one pack" through barcodebuddy?

**Comment by Forceu** [comment]
Hi, there are two ways to do that:

You can either scan the barcode "BBUDDY-Q-20" after scanning your product to tell BarcodeBuddy to always add 20 items when this code is product is scanned, or you can go to Settings and enable "Use Grocys quantity conversion", which should the respect the conversion you set in Grocy.

**Comment by ZeGuigui** [comment]
Thanks! 
I have set the setting to use grocy quantity conversion
