### ISSUE TITLE
Long product title hide create product buttons

### ISSUE THREAD

**Issue by ZeGuigui** [Forceu/barcodebuddy#88]
This is a vuejs issue.

When scanning products with very long names, it hides some columns. You have to scroll to the bottom of the list, scroll to the right, then click the button (or have a mouse with horizontal scroll feature which I happily own!)

![Capture d’écran 2020-08-17 à 23 38 19](https://user-images.githubusercontent.com/13727111/90447101-e5bfbb80-e0e2-11ea-91f3-a8777c333587.png)

**Comment by Forceu** [comment]
Thank you for your report! This is a known problem, but I will probably fix it in the next version.

**Comment by Forceu** [comment]
Fixed in 5eabeafaf36f3ca94308823576ab25427a1b7dff
