### ISSUE TITLE
screen.php cannot connect to websocket server

### ISSUE THREAD

**Issue by ZeGuigui** [Forceu/barcodebuddy#89]
When browsing barcodebuddy/screen.php I only get reconnecting message.
Settings page show websocket server status is running. I tryed changing the port.
Chrome and Firefox the same.
Developper console show sse_data.php taking a long time (60s) to load. I probably missed something on install but I don't know where to start looking (pretty new to websockets myself)

barcodebuddy is installed as an alias in an existing SSL enabled domain. No special configuration done for websockets inside my apache configuration

`screen -ls
There is a screen on:
	18896.bbuddyserver	(17/08/2020 22:19:15)	(Detached)
1 Socket in /var/run/screen/S-root.`

Screenshots attached:
![Capture d’écran 2020-08-18 à 10 11 47](https://user-images.githubusercontent.com/13727111/90487987-82ae4300-e13b-11ea-9e4b-d74e56383ed7.png)
![Capture d’écran 2020-08-18 à 09 57 31](https://user-images.githubusercontent.com/13727111/90488003-8772f700-e13b-11ea-82e9-a6a892aa1afe.png)
![Capture d’écran 2020-08-18 à 10 12 33](https://user-images.githubusercontent.com/13727111/90488039-93f74f80-e13b-11ea-9d3b-8b5e7228b8fa.png)

**Comment by ZeGuigui** [comment]
wsserver is listening on localhost... no wonder I cannot connect from a remote host!

**Comment by Forceu** [comment]
Yes, this is done on purpose, as by default the connection is not encrypted. You can however either use a reverse proxy with encryption or manually edit the https://github.com/Forceu/barcodebuddy/blob/master/wsserver.php file.
