### ISSUE TITLE
Feature-request: Add productsearch.gs1.se

### ISSUE THREAD

**Issue by mcfrojd** [Forceu/barcodebuddy#92]
Is there someone that could get the swedish site productsearch.gs1.se to be used as a barcode lookup provider?

An call to an adress of `https://productsearch.gs1.se/?query=7310865085733` would return a page with some information about the product.
(the last digits is the barcode ofcource)

On that first page there is an "manufactuer code" that is included in an url that would give you the full detalis of the product.
`https://productsearch.gs1.se/details/07310865085733-7310865000002`
Maybe someone with some good knowledge about web scraping could make a barcode lookup provider out of this?

**Comment by Forceu** [comment]
Looks good, I will have a look next week if it is possible to implement.

**Comment by Forceu** [comment]
Okay, so it looks like there is an invisible captcha and that the details are loaded by Javascript. For now I am unable to load support this provider, but if anyone else is able to do so, I would be happy to integrate it.
